### ISSUE TITLE
Excel Custom Functions Return #N/A on build 11328.2008

### ISSUE THREAD

**Issue by keyur32** [OfficeDev/Excel-Custom-Functions#101]
Build 113298.2008 has an issue that prevents Excel Custom Functions from running. This issue has been fixed that will be rolling out as another update to Insiders in a couple of days.

If you haven't updated your build, wait for a few days (we'll close this issue when fixed). Otherwise, you can continue to build your solution on Excel Online.  Sorry for the inconvenience!

**Comment by eldargum** [comment]
Thanks @keyur32 , we're waiting.

**Comment by keyur32** [comment]
This updated build has started rolling out to the Insiders Fast, it will be build 16.0.11330.20014. Currently at 25% and should be resolved over the next day or two.

thanks!

**Comment by keyur32** [comment]
It appears this build has been deployed out to 100% on the Insiders channel. Marking this as fixed.  Please update your Office build to **16.0.11330.20014**

**Comment by eldargum** [comment]
@keyur32 , I upgraded to 11406 build but the custom function returns #VALUE!

**Comment by keyur32** [comment]
Hey @eldargum, yea, sorry, this issue got fixed but then we had another issue come in: https://github.com/OfficeDev/Excel-Custom-Functions/issues/115

**Comment by keyur32** [comment]
Closing this one, as we'll track the other one on the 11406 build.
