### ISSUE TITLE
Streaming Custom Functions will not re-calculate using Office JS Calculate API

### ISSUE THREAD

**Issue by keyur32** [OfficeDev/Excel-Custom-Functions#102]
Excel custom functions currently won't recalculate when performing the calculate event.

**Comment by keyur32** [comment]
Based on partner input, Excel has a new behavior where for streaming functions, we will cache and batch calls that have the same parameters, to become more inline with the =RTD() function behavior that exists currently in Excel.

**Comment by wamaina** [comment]
@keyur32, are there any updates on this bug?

**Comment by keyur32** [comment]
I'm going to close this issue as By Design. Ideally you should use streaming functions to cache new values on a periodic basis.  In this case, the function when reported was using the streaming function to display an intermittent value vs updating state. If the state changes, the function will recalculate and return a new value, so I don't think it will be common.
