### ISSUE TITLE
Excel Online: Functions getting stuck on #GETTING_DATA

### ISSUE THREAD

**Issue by keyur32** [OfficeDev/Excel-Custom-Functions#103]
Certain times, we have seen custom functions evaluate it and then after a bit, start returning #GETTING_DATA.

**Comment by keyur32** [comment]
Ask: If partners are seeing this issue, please add a comment below with repro steps or cases when you see this.

**Comment by 4tti** [comment]
Actually, I've checked it yesterday and I was not able to get custom functions working on Excel online always seeing this #GETTING_DATA error, refresh did not help (and the custom function is simple function returning just hard-coded string).

**Comment by keyur32** [comment]
Thanks @4tti, do you have a scriptlab gist you can share with the simple function? That can help use debug?  
Also, note, if #GETTING_DATA will shown if the function never returns. This could be due to your function not being able to resolve the promise.

(Btw, we did identify an issues intermittent #GETTING_DATA and this fixed has been checked in, will likely be available in ~March).

**Comment by 4tti** [comment]
Hey @keyur32, no I don't have it, I would have to replicate. I just created sample with Test function which does not have any callback, simply returns "Test" string. But I did not check it from last week, maybe it is already fixed. I can get back here once I have a bit more time to check it.

**Comment by keyur32** [comment]
Hi @4tti, we were able to find a repro internally and have deployed the fix. Marking this as fixed.

**Comment by keyur32** [comment]
Marking as closed
