### ISSUE TITLE
Repeating Parameters [tracking item]

### ISSUE THREAD

**Issue by keyur32** [OfficeDev/Excel-Custom-Functions#107]
We will plan to have repeating parameters after Custom Functions will become GA. This is a tracking issue for that.

General idea would be to declare: {"repeating": true} for your parameter

**Comment by keyur32** [comment]
Should be available on office online. Will resolve when tooling and docs are ready.

**Comment by mscharlock** [comment]
Adding myself to this to keep track of the docs work here :)

**Comment by wamaina** [comment]
@mscharlock and @keyur32, is the work required in progress? Is this item still under investigation?

**Comment by mscharlock** [comment]
Ah this should be closed, repeating params is out and docs are up. I'll go ahead and close.

**Comment by akrantz** [comment]
@keyur32 Script Lab should now support repeating parameters. It would be good to validate.
