### ISSUE TITLE
Example functions return #N/A

### ISSUE THREAD

**Issue by OSjoerdWie** [OfficeDev/Excel-Custom-Functions#109]
Prebuilt custom function does not seem to work on Excel Desktop.

## Article URL
https://docs.microsoft.com/en-us/office/dev/add-ins/tutorials/excel-tutorial-create-custom-functions?tabs=excel-windows

## Issue
Following the steps until **Try out a prebuilt custom function** went successful. However, after entering =CONTOSO.ADD(10;200) the result went from "#GETTING DATA"  to "#N/A" instead of 210 in Excel Desktop. On Excel Online all seems fine.

**Comment by akrantz** [comment]
See #101
