### ISSUE TITLE
The Add-In loaded correctly, but there is no CONTOSO function

### ISSUE THREAD

**Issue by yuyueugene84** [OfficeDev/Excel-Custom-Functions#112]
The Add-In did show on the sidebar for me, but when I try out the CONTOSO function in step 5, excel did not have such a function.  I'm using 64-bit Excel with Insider program, and already configured the Trusted root certification in step 3.

(Issue encountered when trying to complete the Excel Custom Functions tutorial: https://docs.microsoft.com/en-us/office/dev/add-ins/tutorials/excel-tutorial-create-custom-functions?tabs=excel-windows.)

**Comment by keyur32** [comment]
Hi @Blacksmoke16, 

Can you try to update your build to 11330 and try again? We did have this issue: #101 and that has been resolved.

If the add-ins are showing and the functions aren't appearing, can you also turn on runtime logging please?

**Comment by Blacksmoke16** [comment]
Updated Excel.  Am now currently on Version 1903 Build 16.0.11406.20002 64-Bit.

I started a new project following the tutorial, but same issue.  

I also tried enabling logging, however it didn't seem to do anything?

![image](https://user-images.githubusercontent.com/12136995/52682613-103d2100-2f0e-11e9-9baf-95c8cd54a98b.png)

**Comment by keyur32** [comment]
thanks! @akrantz can you help take a look? @Blacksmoke16, may be best if we try to debug with you (so we can learn and then document this for others). i'll reach out offline. thanks!

**Comment by keyur32** [comment]
We were able to resolve. Issue is the current preview requires **Office 365 Professional Plus**. It will not work with the **Home and Student** version.

**Comment by keyur32** [comment]
Marking as closed
