### ISSUE TITLE
XHR/Fetch requests return #VALUE! on Windows build 16.011406.20002

### ISSUE THREAD

**Issue by keyur32** [OfficeDev/Excel-Custom-Functions#115]
Custom Functions on Windows that use XML or Fetch will see #VALUE! as the XHR call may fail.

To workaround, please use: Use Mac or Excel Online

**Comment by keyur32** [comment]
Will be fixed in the next build

**Comment by keyur32** [comment]
This has been fixed and we are waiting the next build to rollout to Insiders Fast channel.

**Comment by keyur32** [comment]
The build has now been deployed. Please update your build to **Version 1903 (11414.200014)**

**Comment by eldargum** [comment]
@keyur32 thanks! it's working. But when I use XMLHttpRequest to my local IIS I see only #GETTING_DATA and #VALUE! after 1-2 minutes as a result of my custom function. I copied the certificate to trusted folder.
And second question  - when will the Custom function be in Production, not Preview?

**Comment by keyur32** [comment]
Hey @eldargum, what build are you seeing this under? On Windows, Online or Mac?

(We're hoping to stabilize these last set of issues and we'll be close to getting add-ins with custom functions ready for GA (at least our V1) -- barring any last minute issues; so please continue to report bugs! :)

**Comment by eldargum** [comment]
Hi @keyur32, I use 11414.20014 build on Windows.

**Comment by keyur32** [comment]
Thanks, can you also share the runtime log. You can ping me directly: kepatel@microsoft.com. thanks!

**Comment by keyur32** [comment]
Marking this closed as it is something related to the developer environment (still checking to see what that culprit is for that ).
