### ISSUE TITLE
[Tracking item] Support for cookie based authentication between Custom Functions and Taskpane/Dialog

### ISSUE THREAD

**Issue by keyur32** [OfficeDev/Excel-Custom-Functions#118]
Currently we have support in the custom functions runtime to pass tokens between the taskpane and dialog to the custom function via Async Storage.

This doesn't work for cookie based authentication as the httpOnly cookie is not exposed to Javascript by the browser.

Team needs to evaluate this ask and prioritize accordingly based on what we can do.

**Comment by 4tti** [comment]
@keyur32: extremely important case.

**Comment by esbanarango** [comment]
➕ for this to be supported

**Comment by keyur32** [comment]
This is now rolling out on Insiders, but requires some updates to the manifest. We'll revert back once documentation is ready.  For now stay tuned to our Office add-ins community call by signing up at: https://aka.ms/officeaddinscommunitycall.  We will announce when it is ready there.  Closing this for now! thanks!

**Comment by ElizabethSamuel-MSFT** [comment]
@keyur32 What's the current status? Thanks.

**Comment by keyur32** [comment]
Closing this, as Shared Runtime is now Generally Available and unblocks this use case: https://developer.microsoft.com/en-us/office/blogs/power-up-with-office-add-ins-build-2020/
