### ISSUE TITLE
[FYI] #GETTING_DATA will be changing to "#BUSY!"

### ISSUE THREAD

**Issue by keyur32** [OfficeDev/Excel-Custom-Functions#120]
We are changing the status that custom functions show while calculation.

Why?
1. #GETTING_DATA wasn't accurate in all cases.
2. #GETTING_DATA caused users columns to resize (so trying to decrease width for most locales).

Build you will start seeing this: Any build > 16.0.11505.10000.

**Comment by delium** [comment]
acroding to your note, we should already see this but we don´t. my excel online version 16.0.11506.35050

also always getting some error message, see attatchment:
![image](https://user-images.githubusercontent.com/7172621/54093139-a2610980-4394-11e9-83f0-8935a43cfed3.png)
![image](https://user-images.githubusercontent.com/7172621/54093147-b4db4300-4394-11e9-8701-43e04b35fcb2.png)

**Comment by keyur32** [comment]
Hey there, this hasn't yet deployed (at least on the Windows Insiders Fast build, was was still on 16.0.11425.20036). Online is slightly behind as far as I'm aware so it doesn't surprise me that is not there either.

**Comment by keyur32** [comment]
Should be updated
