### ISSUE TITLE
Sample not working on Mac

### ISSUE THREAD

**Issue by GeorgeHung** [OfficeDev/Excel-Custom-Functions#122]
I was trying the sample from https://github.com/OfficeDev/Excel-Custom-Functions on my mac, all the functions returns #GETTING_DATA other than the log function.  It is probably probably because Excel has a log function already.  I am using version 16.24(190306).

**Comment by keyur32** [comment]
@akrantz - can you help take a look at this one one? 

@GeorgeHung  - yes, current behavior if you create a function that matches a built-in function name, that built -in function takes precedence and executes (unless it has a namespace), which is similar to VBA behavior.

**Comment by akrantz** [comment]
The sample uses CONTOSO as the namespace so CONTOSO.LOG should not conflict with built-in LOG function. I will investigate further.

**Comment by GeorgeHung** [comment]
I just upgraded to build 190310, and not the functions return #VALUE!.

**Comment by akrantz** [comment]
@GeorgeHung I will look into this today.

**Comment by akrantz** [comment]
@GeorgeHung This should be fixed now. Please let me know if it works for you.

**Comment by GeorgeHung** [comment]
Can you tell me which build should have the fix?

**Comment by akrantz** [comment]
The same one. There was a misconfiguration that should be updated to resolve the issue.

**Comment by GeorgeHung** [comment]
I tried apply your change of removing the requirement set in the manifest, and then the ADD function returns #BUSY!.  Are there other change I need to apply?

**Comment by akrantz** [comment]
No. The <Requirements> in the manifest won't have any effect. It was only removed because manifest validation fails right now for it.

The fact that #BUSY! shows is good, and it should shortly show the actual value afterwards. Was it able to complete?

**Comment by GeorgeHung** [comment]
No the value stays as #BUSY!.

**Comment by akrantz** [comment]
@GeorgeHung Hi George, can you please check again?

**Comment by GeorgeHung** [comment]
It is still not working.  Do I need to update anything before I try it?

**Comment by akrantz** [comment]
You might check for updates. I am trying 190313 right now.

**Comment by GeorgeHung** [comment]
I just updated to 190313, and still no luck.

**Comment by akrantz** [comment]
Are you on Insiders Fast?

**Comment by GeorgeHung** [comment]
Yes.  I am on insider fast.

**Comment by GeorgeHung** [comment]
The strange things it that our custom functions are working.  However, the custom functions in the sample aren't.

**Comment by akrantz** [comment]
Agreed. There are docs online about clearing the cache. Maybe that will help resolve the issue.
