### ISSUE TITLE
Debugging

### ISSUE THREAD

**Issue by chris-trotter** [OfficeDev/Excel-Custom-Functions#13]
I'm having great difficulty debugging the custom functions I am writing. I have attempted to follow the instructions to enable the debugger through IE settings, while running the F12Chooser.exe application (it appears to inconsistently find the relevant excel window).

I have have created a httpRequest function, but have received the #GETTING_DATA placeholder and no error is being presented.

Is there a better or more reliable way to review errors? I am sorely missing chrome/node debugging.

**Comment by jimmcslim** [comment]
I can't help you but to agree that the state of debugging Excel Javascript add-ins is indeed a bit tedious. I can only hope with this announcement -> https://blogs.windows.com/msedgedev/2018/05/11/introducing-edge-devtools-protocol/ that maybe better times maybe ahead, but this is probably contingent on Excel integrating Edge rather than whichever version of IE it currently uses.

**Comment by chris-trotter** [comment]
@jimmcslim thanks! This may be a stupid question but is there a way to review console logs from within excel addons?

**Comment by eldargum** [comment]
@jimmcslim can I run TaskPane and Customfunctions at the same time for debugging with F12? I'm trying add TaskPane action to manifest but Excel crushed when I inserted add-in.

**Comment by keyur32** [comment]
Hi folks, just following up on this thread. Right now, we're working on enabling debugging for the custom functions runtime (which is not dependent on the browser). 

That said for now, a good option to debug your logic is to sideload your add-in on https://www.office.com/ in Excel Online  (Insert > Add-ins > Manage My add-ins > Upload...). There you can use the F12 tools to debug both custom functions and your taskpanes.  

Will reply back when debugging from VS code is available for custom functions on Excel desktop.
