### ISSUE TITLE
Question: How to pass configuration parameters to custom function's JavaScript context

### ISSUE THREAD

**Issue by alaincao** [OfficeDev/Excel-Custom-Functions#130]
Hello there, this is more a question than an issue ; I hope this is the right place to ask ...  

How can I pass general server configuration values to the custom functions context?  
e.g. I have no problem within the taskpane context because I have access to a DOM where I can generate things like  
```html
<script>
window.myparameters = { napoleonsWhiteHorseColor:"Probably black" };
</script>
<script src="myaddin.js"/>
```  
but I have difficulties understanding how to do that for the CustomFunctions context since there is no HTML file nor DOM...  
I mean, without access to `window.location.href`, I'm not even sure how to get the current server's URL (without hard-coding it which I am definitively not going to do) ; I could use that to make some request to`/someoptionalvirtualpath/myparameters.json`.  

I thought about polling the AsyncStorage regularily and wait for the taskpane to post them there, but that really doesn't seem right ...

Subsidiary question: is there a way to use more than 1 JavaScript file for the CustomFunctions context? I haven't seen any way in the `manifest.xml`.  
e.g. { file_1: "http://server/parameters_generated.js", file_2: "http://server/myaddin.js" }

Thank you!

**Comment by akrantz** [comment]
Yes, AsyncStorage can be used to write the configuration info from the taskpane code and then be read from the custom functions code.

You need to bundle the JavaScript for custom functions into a single file. The code here uses webpack for this.

**Comment by alaincao** [comment]
Ok, I see, that's what I feared. Thank you for the response.  

So my question becomes: will there ever be some kind of "push notifications" between the CustomFunctions and taskpane contexts like `Office.context.ui.messageParent()` that is used between popup windows and their parent?  

Sorry, another one: where are stored the `AsyncStorage` values (when used from the online Excel) ?  
In the browser's local storage or would it require some HTTP requests to some server ?  
i.e. what would be the performance impact of using them / what would be the stored values lifetime?
I haven't found an answer to this in the documentation.

**Comment by keyur32** [comment]
Hi @alaincao, yes, we are working on a 'dispatch' model so you don't have to continuously poll. This will be a way to send messages and won't persist to disk. We'll share info during our Custom Functions call, but will not on our V1.  Fill this out if you want to join our weekly call and I'll reach out: https://aka.ms/customfunctionscall.

On Excel Online (and currently on Mac), AsyncStorage uses the browsers localstorage. I'll make a note for @davidchesnut / @mscharlock  to add this to docs. thanks!

**Comment by Reezaali** [comment]
Internal bug# 3281128

**Comment by davidchesnut** [comment]
Just an update that we published info about the Storage object usage of browser localstorage on the Mac (around May 1). See https://docs.microsoft.com/office/dev/add-ins/excel/custom-functions-save-state. @keyur32 I'll remove myself from the assignee list on this issue. Thanks!

**Comment by kkliebersbach** [comment]
@keyur32 Thanks for the updates on this issue! Just wondering what the current status is on the new "dispatch" model? We have some functionality ready to go with this feature :slightly_smiling_face:

**Comment by keyur32** [comment]
We are working on the documentation and release for insiders right now :)

**Comment by ElizabethSamuel-MSFT** [comment]
@davidchesnut Any update on this? Thanks.

**Comment by davidchesnut** [comment]
Hi @alaincao, following up on this thread, we have a preview feature that allows you to put the custom functions in the same context as the task pane, so they are both effectively using the same DOM. You can then share data or call functions as needed. For more information see [Tutorial: Share data and events between Excel custom functions and the task pane (preview)](https://docs.microsoft.com/office/dev/add-ins/tutorials/share-data-and-events-between-custom-functions-and-the-task-pane-tutorial). This is the planned solution to your question going forward. Please let us know if you have any feedback on this approach. Thanks!

**Comment by keyur32** [comment]
Marking closed as it looks to not have had any response since last note. Please re-activate if further help is still needed.  The feature David mentioned above, was using the Shared Runtime, and is also now generally available. Thanks!
