### ISSUE TITLE
OfficeRuntime.AsyncStorage API name change to "OfficeRuntime.Storage" 

### ISSUE THREAD

**Issue by keyur32** [OfficeDev/Excel-Custom-Functions#133]
Hey folks,

OfficeRuntime.AsyncStorage to OfficeRuntime.Storage.  Your existing add-ins will continue to work for a short period of time as this is one of the last items we want before we announce general availability!  It will be available along with custom functions in our production CDN in a few weeks time.

**Comment by TheWass** [comment]
Will the new OfficeRuntime.Storage still be async?  Just a name change?

**Comment by keyur32** [comment]
Hi this, is now available at:

https://appsforoffice.microsoft.com/lib/1.1/hosted/office.js
https://appsforoffice.microsoft.com/lib/1.1/hosted/custom-functions-runtime.js

@mscharlock, @davidchesnut  to update documentation on.

**Comment by mscharlock** [comment]
Documentation updated!
