### ISSUE TITLE
Question: What is the timeline for not requiring Insider Level status?

### ISSUE THREAD

**Issue by noon-otter** [OfficeDev/Excel-Custom-Functions#135]
Ie. is there a future where this project supported for use in production environments?

**Comment by keyur32** [comment]
Soon! Keep a look out here and I will circle back when we are available. 

We would also love to hear what you are building as well. Can you fill out https://aka.ms/customfunctionscall?

**Comment by noon-otter** [comment]
Thanks! I'm looking forward to that. I'm building out an excel add-in with a panel and custom functions, and it'd be valuable to write the entire project in react/typescript - including the custom functions. The plan is to distribute it internally at my company, but I can't have every user sign up for insider status to use it.

Love the project so far. Developing for excel is much easier nowadays. What does "soon" mean? Weeks, months, quarters? Can't wait for this to be pushed to prod.

**Comment by keyur32** [comment]
Keep an eye out to our channels and you will hear this “soon” enough:)

**Comment by bestekov** [comment]
Looks like the answer is... today? 

https://developer.microsoft.com/en-us/office/blogs/office-extensibility-build-2019/

**Comment by keyur32** [comment]
Yes!! Build is rolling out over next day or two. You should be able to try now. Thanks for waiting!

________________________________

**Comment by keyur32** [comment]
Marking closed as we are now GA :)
