### ISSUE TITLE
Feature request: Caller.address should also provide the workbook name

### ISSUE THREAD

**Issue by TheWass** [OfficeDev/Excel-Custom-Functions#137]
I'm working on a set of Custom Functions which needs to store data tied with an individual document.  There currently is the AsyncStorage feature to interlink with the Taskpane, and the Taskpane can grab the settings data off of the document.  However, the AsyncStorage is shared across all documents.  Having a document identifier would allow data in AsyncStorage to be tied to specific documents.

Could you add a document ID or similar mechanism which uniquely identifies the document that the custom function is running on?

**Comment by keyur32** [comment]
Thanks. We will consider this, I see how the caller.address capability doesn’t include the workbook name so becomes hard to create the association. One idea could be to set a key in async storage for the value you want to store. On the taskpane you could also write that key to the document settings object and retrieve it afterwards.

**Comment by TheWass** [comment]
Thanks for your response!  I had considered that, and I'll probably go with that solution for the time being, the trouble occurs when you have multiple workbooks open simultaneously.  All of the workbooks read from the same Async storage.

**Comment by keyur32** [comment]
Closing this issue for now. Since you can now get the worksheet name via the Shared Runtime (initialize your taskpane, get worksheet name, save it to a global, and then access it from your function).
