### ISSUE TITLE
WebService

### ISSUE THREAD

**Issue by Peteratrapporr** [OfficeDev/Excel-Custom-Functions#14]
I working on this and want to pull data from a remote server, but I can't get it working.

In the documentation, XHR is talked about but there is no example.  Have tried to use XMLHttpRequest, but get an N/A.

Would like some example code so I can then start building out my project

**Comment by chris-trotter** [comment]
https://gist.github.com/chris-trotter/86384e7595d81b3f94a0122c85b92c4a

Have a look at this gist. You can add this function to your project. You have to use the OfficeExtension.Promise and pass the response from the httpRequest function to the promise's resolve function.

I went about using a simple xmlhttprequest as I couldn't debug the errors when trying to import standard http libraries.

**Comment by chris-trotter** [comment]
@Peteratrapporr If you receive #N/A then perhaps your function has defined an expected type of number rather than the string you are returning with. If you want further support I suggest uploading your project to a github repository.

**Comment by Peteratrapporr** [comment]
It is returning a string and works with the return function. The return value is a string as well for

[excel.zip](https://github.com/OfficeDev/Excel-Custom-Functions/files/2041983/excel.zip)

 this, but not even reaching this.

This is the only function and is part of the tutorial which I have modified to test if this works before I get fully working on this.

Filename is customfunctions.js

**Comment by chris-trotter** [comment]
@Peteratrapporr You've forgotten to add `"dimensionality": "scalar"` key and value to your result object.
```
			"result": {
				"type": "string",
				"dimensionality": "scalar"
			},
```
See my below fork of the sample project for further examples of xmlhttprequests to an API.
https://github.com/chris-trotter/companies-house-excel-custom-functions

**Comment by Peteratrapporr** [comment]
Thanks.

Have taken this code base and copied parts across to this make this work and now getting #GETTING_DATA in the cell, but no data.

Have noticed the call to my server was a OPTIONS type instead of GET. Altered code to handle this and return data. Tested with POSTMAN and is working.

Tested calling your service as well and got the same result.

**Comment by Peteratrapporr** [comment]
Have got it working. My server was blocking due to content type rule.

Don't know why your server wasn't working as now working.

**Comment by Peteratrapporr** [comment]
Have it working, but my services return JSON objects, not just text data

Can't access the values as an object eg reply.Name.  If I try to convert to a string, it fails as well.

**Comment by chris-trotter** [comment]
I'm doing all data operations and manipulations through a node script on my server and then handing the end text result to excel. Debugging a server-side node script is much easier than attempting to debug data manipulations on the excel client side. Keep your client side code as simple as possible until there's a decent debugger.

**Comment by Peteratrapporr** [comment]
The server code is what I'm already doing with Google Sheets which I'm now converting to Excel and I use Google Sheets cache function.

Could have a sheet with 1,000 cells to be updated (weekly cashflow). The Cache model with Google allows me to update the sheet in 8 seconds and only do 12 calls to the server for each of the weeks involved which cuts down the server hits. This data is coming from Xero accounting software [www.nowfunctions.com](url)

Really need to know how to access the JSON object. 

Been through debug hell like this before as had it with Google Sheets as well.

**Comment by eldargum** [comment]
@chris-trotter thanks for sharing your project! I created API for SQL Server using Node.js and trying to receive the data to excel with custom functions, one or two rows work fine, but when I'm filling data automatically 1000 rows for example I got 500 err in the some cells.

**Comment by chris-trotter** [comment]
@eldargum You should test to ensure your API is not rate limited. My project above is using a Companies House API which is rate limited to 500 requests per 5 minutes.

**Comment by eldargum** [comment]
@chris-trotter thanks  for answers! After that I created small http handler demo using .NET and this work is fine, so the issue related with nodejs code, not with Excel custom function.

**Comment by Peteratrapporr** [comment]
Not rate limited as my code acting as the middleware to handle rate limiting of other systems.  I'm actually running a "GO" backend and have done the JSON stuff before. The issues is the reply from the promise is an object. If passed straight  to the cell, it handles this, but I want to extract the data first.

**Comment by keyur32** [comment]
Hi all, it looks like this thread was resolved. Yay. If you need more info about making web calls, please see the documetnation on the custom functions runtime: https://docs.microsoft.com/en-us/office/dev/add-ins/excel/custom-functions-runtime
