### ISSUE TITLE
Problem with using OfficeRuntime.storage in existing Excel Add-in

### ISSUE THREAD

**Issue by margosmat** [OfficeDev/Excel-Custom-Functions#148]
I'm trying to share some data between my existing Excel Add-in taskpane and newly added custom-functions. When I'm trying to set/get value I get "NotImplemented: Not implemented." error.

I'm referencing this package in my taskpane page:
```
<script src="https://appsforoffice.microsoft.com/lib/1.1/hosted/office.js"></script>
```

And I use storage in my taskpane this way:
```typescript
OfficeRuntime.storage.setItem('someData', someData)
    .then((result) =>
    {
      console.log(result);
    }, (error) =>
    {
      console.log('Store error: ');
      console.log(error);
    });
```

I also use Typescript in my add-in, so I've added 
```
"@types/office-runtime": "^1.0.7"
```
package for types.
I've seen in some examples OfficeRuntime.AsyncStorage used, but I can't use it, as it isn't available in the IntelliSense.

Also I want to add that I have Excel version 1904 (Build 11601.20204) and Windows 10 version 10.0.17763 Build 17763

**Comment by akrantz** [comment]
AsyncStorage was the old name. It was renamed to Storage.

Here's an example that I think should help you: 
https://github.com/OfficeDev/PnP-OfficeAddins/tree/master/Excel-custom-functions/AsyncStorage

**Comment by margosmat** [comment]
I think that my problem was related to this: [[Excel] OfficeRuntime.AsyncStorage or OfficeRuntime.storage does not work in TaskPane](https://github.com/OfficeDev/office-js/issues/522).
Good news is that it works now ;)
