### ISSUE TITLE
[Tracking Item] Returning built in errors from a custom function

### ISSUE THREAD

**Issue by keyur32** [OfficeDev/Excel-Custom-Functions#149]
Currently, when you throw an error it returns #VALUE!.  This work item captures the plan to allow for a custom function to return a built in error, with a custom error message (which will be shown in a popup menu in Office 365).

**Comment by keyur32** [comment]
This is fixed, will share on a future community call :)

**Comment by 4tti** [comment]
@keyur32: is there some documentation how to use it? Thanks!
