### ISSUE TITLE
#NAME? Error In Spreadsheet

### ISSUE THREAD

**Issue by KD33** [OfficeDev/Excel-Custom-Functions#15]
Hello, I've followed the instructions to the best of my knowledge so please bare with me.
I tried running  = CONTOSO.ADD42(A1) where cell A1 is the number 1, and get a #NAME? error in Excel.  So far I've

1)Am an office insider member and have a build version of 16.13.1
2)Cloned the repo, set up a server on port 3000 to serve the static files using Express
3)Changed localhost:8000 to localhost:3000 in the manifest file.  
4)Sideloaded the add-in to the wef folder.  I'm able to load the add-in in Excel (I get the iframe), but get the name error whenever I try to use any of the functions.

Thanks

**Comment by govert** [comment]
I needed to install the "Insider" (Fast) version - having "Monthly Channel (Targeted)" (Slow) which was the default install even as an Office Insider did not work.

So in File -> Account it reads:
![image](https://user-images.githubusercontent.com/414659/40879865-8ed02466-66a7-11e8-806e-b75de098ec79.png)

**Comment by KD33** [comment]
That did the trick.  Appreciate it.
