### ISSUE TITLE
Debug formula in Excel cell

### ISSUE THREAD

**Issue by smozgur** [OfficeDev/Excel-Custom-Functions#151]
We can debug a formula in Excel cell by using F9 key. For example we can select the range in a formula - A1:B3 below-, and hit F9 to see the values in the given range in array form to evaluate the values:

`=SUM(A1:B3) returns to =SUM({1,4;2,5;3,6})`

In Excel Custom Functions, this feature doesn't work. It simply converts to #VALUE! as soon as you hit F9.

`=CUSTOM.SUM(A1:B3) returns to =CUSTOM.SUM(#VALUE!)`

**Comment by keyur32** [comment]
Hi @smozgur, yes this currently is not yet supported with Custom Functions. We need to do some additional work here as JS Custom Functions are executed differently than most other functions -- meaning they are asynchronous and out of process.

This also is the case of getting #VALUE! in the formula evaluator, or when performing a calculating that involve the Excel Data Tables feature.

**Comment by smozgur** [comment]
> they are asynchronous and out of process.

Makes sense. Thank you @keyur32.

**Comment by keyur32** [comment]
Closing this issue for now, but is tagged internally. We'll see if we can improve upon this case in the coming months. Thanks!
