### ISSUE TITLE
Question: 32-bit Support

### ISSUE THREAD

**Issue by RichardBruckshaw** [OfficeDev/Excel-Custom-Functions#157]
Hi, this is more a question than an issue, I hope this is the right place to ask ...

Are there any plans to support 32-bit Excel?  I would love to use this for a project that I am starting, but our organisation is stuck with 32-bit Office and moving to 64-bit would be a fairly major undertaking.

**Comment by keyur32** [comment]
Hi @RichardBruckshaw, yes, we do support 32 bit! 

 I think the tutorial may have a doc bug that is going to get fixed that says it needs 64 bit (which during developer preview, we had recommended).

**Comment by RichardBruckshaw** [comment]
Amazing.  Thank you.

**Comment by keyur32** [comment]
N/P, out of curiosity, what are you building?

**Comment by RichardBruckshaw** [comment]
We are looking to expose a bunch of our internal services (financial data and portfolio construction functionality) to Excel users across our organisation.  This solution is super attractive as we can use Javascript, doesn't require installing anything on the end users machine and it can be used with office online as well other operating systems.

**Comment by RichardBruckshaw** [comment]
Do you know what build number this functionality was included in?
