### ISSUE TITLE
Excel: Sample custom functions fail to install; #NAME? when using custom functions

### ISSUE THREAD

**Issue by andrewbridge** [OfficeDev/Excel-Custom-Functions#158]
Hi there,

I've been trying to get the sample to work out of the box as per the instructions on the [Getting Started](https://docs.microsoft.com/en-us/office/dev/add-ins/quickstarts/excel-custom-functions-quickstart?tabs=excel-windows) page.

The project initialises as expected, I build the project with `npm run build` as per step 3, then `npm run start:desktop` as per step 4.

The dev server starts successfully, webpack runs successfully and Excel opens with the project sideloaded into it. The task pane renders correctly and I'm able to make updates to it. But along the bottom I see the following:

![image](https://user-images.githubusercontent.com/2941908/59037213-be2b5d00-8868-11e9-83c0-f6b5bbb31af9.png)

If I use the "Attach Debugger" option in the Task Pane, an old IE warning appears stating

`office.js has not fully loaded. Your app must call office.onready()`

Having not changed any of the code, the...

```js
Office.onReady(info => {
  // If needed, Office.js is ready to be called
});
```

...block is still in place in the command.js (or .ts) file but as far as I've been able to tell, this block of code is never run.

I've checked the following issues on this repo:

- https://github.com/OfficeDev/Excel-Custom-Functions/issues/112 - I have trusted the certificate, see top of webpack-dev-server output. I am also using Excel Version 1905 (Build 11629.20214) activated with a Microsoft Office Professional Plus 2019 account
- https://github.com/OfficeDev/Excel-Custom-Functions/issues/104 - I don't believe this is related, but I have tried changing the namespace for the functions multiple times in case a conflict is occurring. This does not change the above behaviour
- https://github.com/OfficeDev/Excel-Custom-Functions/issues/15, https://github.com/OfficeDev/Excel-Custom-Functions/issues/6, https://github.com/OfficeDev/Excel-Custom-Functions/issues/2 - [As discussed on StackOverflow](https://stackoverflow.com/questions/47211087/excel-custom-functions-contoso-add42-function-is-not-appearing-in-excel), Version 1810/8711 or later is required, but as this appears to have been released since the ticket and SO post, can assume I no longer need to be in the Insider program? I can't see this requirement listed anywhere, but when I have tried to [join the program](https://insider.office.com/en-us/join), the instructions listed don't relate to the options I'm given in my version of Excel
- https://github.com/OfficeDev/Excel-Custom-Functions/issues/136 - This issue is almost identical to my situation, including the log which cuts out during the CustomFunction Registration (see excel-log.txt output below). However, as the user never updated the ticket or appeared to follow up the issue, this issue is a bit of a dead end.

I have tried running these steps via VS Code, a JetBrains IDE, a bash console, a cmd prompt, both with a Javascript and Typescript configuration.

~My only thought is that I appear to be running a 32-bit version of Excel, but as per https://github.com/OfficeDev/Excel-Custom-Functions/issues/157, this shouldn't be an issue as far as I can see.~ _I reinstalled with a 64-bit version, just in case, but this didn't change the situation._

#### Environment

- Platform: PC Desktop
- Host: Excel
- ~Office version number: Microsoft Excel 2019 MSO (16.0.11629.20210) 32-bit; Version 1905 (Build 11629.20214 Click-to-Run)~
- Office version number: Microsoft Excel 2019 MSO (16.0.11629.20210) 64-bit; Version 1905 (Build 11629.20214 Click-to-Run)
- Operating System: Windows 10 Enterprise N; Version 1809; OS build 17763.504

-----

#### webpack-dev-server output
```sh
You already have trusted access to https://localhost.
Certificate: C:\Users\AndrewBridge\.office-addin-dev-certs\localhost.crt
Key: C:\Users\AndrewBridge\.office-addin-dev-certs\localhost.key
C:\dev\Derivitec Excel Add-in\dist\functions.json created for file: ./src/functions/functions.ts
i ｢wds｣: Project is running at https://localhost:3000/
i ｢wds｣: webpack output is served from /
i ｢wds｣: Content not from webpack is served from C:\dev\Derivitec Excel Add-in
i ｢wdm｣: Hash: 76992de46f10372b6682
Version: webpack 4.33.0
Time: 5037ms
Built at: 06/06/2019 11:37:01
                               Asset       Size     Chunks             Chunk Names
7f313c06a52dabe7267420021403d038.png   11.6 KiB             [emitted]
                       commands.html  541 bytes             [emitted]
                         commands.js    342 KiB   commands  [emitted]  commands
                     commands.js.map    391 KiB   commands  [emitted]  commands
                      functions.html  461 bytes             [emitted]
                        functions.js    343 KiB  functions  [emitted]  functions
                    functions.js.map    393 KiB  functions  [emitted]  functions
                      functions.json   1.79 KiB             [emitted]
                         polyfill.js    739 KiB   polyfill  [emitted]  polyfill
                     polyfill.js.map    709 KiB   polyfill  [emitted]  polyfill
                        taskpane.css   1.48 KiB             [emitted]
                       taskpane.html   2.58 KiB             [emitted]
                         taskpane.js    346 KiB   taskpane  [emitted]  taskpane
                     taskpane.js.map    392 KiB   taskpane  [emitted]  taskpane
Entrypoint functions = functions.js functions.js.map
Entrypoint polyfill = polyfill.js polyfill.js.map
Entrypoint taskpane = taskpane.js taskpane.js.map
Entrypoint commands = commands.js commands.js.map
[0] multi (webpack)-dev-server/client?https://localhost:3000 ./src/functions/functions.ts 40 bytes {functions} [built]
[1] multi (webpack)-dev-server/client?https://localhost:3000 @babel/polyfill 40 bytes {polyfill} [built]
[2] multi (webpack)-dev-server/client?https://localhost:3000 ./src/taskpane/taskpane.ts 40 bytes {taskpane} [built]
[3] multi (webpack)-dev-server/client?https://localhost:3000 ./src/commands/commands.ts 40 bytes {commands} [built]
[./node_modules/@babel/polyfill/lib/index.js] 678 bytes {polyfill} [built]
[./node_modules/@babel/polyfill/lib/noConflict.js] 567 bytes {polyfill} [built]
[./node_modules/core-js/library/fn/global.js] 87 bytes {polyfill} [built]
[./node_modules/strip-ansi/index.js] 161 bytes {functions} {polyfill} {taskpane} {commands} [built]
[./node_modules/webpack-dev-server/client/index.js?https://localhost:3000] (webpack)-dev-server/client?https://localhost:3000 4.29 KiB {functions} {polyfill} {taskpane} {commands} [built]
[./node_modules/webpack-dev-server/client/overlay.js] (webpack)-dev-server/client/overlay.js 3.59 KiB {functions} {polyfill} {taskpane} {commands} [built]
[./node_modules/webpack-dev-server/client/socket.js] (webpack)-dev-server/client/socket.js 1.04 KiB {functions} {polyfill} {taskpane} {commands} [built]
[./node_modules/webpack-dev-server/client/utils/createSocketUrl.js] (webpack)-dev-server/client/utils/createSocketUrl.js 2.77 KiB {functions} {polyfill} {taskpane} {commands} [built]
[./src/commands/commands.ts] 752 bytes {commands} [built]
[./src/functions/functions.ts] 1.5 KiB {functions} [built]
[./src/taskpane/taskpane.ts] 4.6 KiB {taskpane} [built]
    + 330 hidden modules
Child html-webpack-plugin for "commands.html":
     1 asset
    Entrypoint undefined = commands.html
    [./node_modules/html-webpack-plugin/lib/loader.js!./src/commands/commands.html] 472 bytes {0} [built]
Child html-webpack-plugin for "functions.html":
     1 asset
    Entrypoint undefined = functions.html
    [./node_modules/html-webpack-plugin/lib/loader.js!./src/functions/functions.html] 394 bytes {0} [built]
Child html-webpack-plugin for "taskpane.html":
                                   Asset      Size  Chunks             Chunk Names
    7f313c06a52dabe7267420021403d038.png  11.6 KiB          [emitted]
     + 1 hidden asset
    Entrypoint undefined = taskpane.html
    [./assets/logo-filled.png] 82 bytes {0} [built]
    [./node_modules/html-webpack-plugin/lib/loader.js!./src/taskpane/taskpane.html] 2.63 KiB {0} [built]
i ｢wdm｣: Compiled successfully.
```

#### excel-log.txt output
```
06/06/2019 14:22:30	Medium	Web Add-In Runtime Logging Session Started			
06/06/2019 14:22:30	Verbose	CustomFunctions	[Installation] [Addin] [Begin] Solution=3212b54a-8567-4afe-8037-97a17bf2a762, Version=1.0.0.0		
06/06/2019 14:22:30	Medium	CustomFunctions	[Installation] [Addin] [End] [Success] Solution=3212b54a-8567-4afe-8037-97a17bf2a762, Version=1.0.0.0		
06/06/2019 14:22:30	Verbose	CustomFunctions	[Metadata] [Parsing] [Begin]		
06/06/2019 14:22:30	Verbose	CustomFunctions	[Metadata] [Parsing] [Begin] Function		
06/06/2019 14:22:30	Medium	CustomFunctions	[Metadata] [Parsing] [End] [Success] Function=CONTOSO.ADD		
06/06/2019 14:22:30	Verbose	CustomFunctions	[Metadata] [Parsing] [Begin] Function		
06/06/2019 14:22:30	Medium	CustomFunctions	[Metadata] [Parsing] [End] [Success] Function=CONTOSO.CLOCK		
06/06/2019 14:22:30	Verbose	CustomFunctions	[Metadata] [Parsing] [Begin] Function		
06/06/2019 14:22:30	Medium	CustomFunctions	[Metadata] [Parsing] [End] [Success] Function=CONTOSO.INCREMENT		
06/06/2019 14:22:30	Verbose	CustomFunctions	[Metadata] [Parsing] [Begin] Function		
06/06/2019 14:22:30	Medium	CustomFunctions	[Metadata] [Parsing] [End] [Success] Function=CONTOSO.LOG		
06/06/2019 14:22:30	Medium	CustomFunctions	[Metadata] [Parsing] [End] [Success]		
06/06/2019 14:22:30	Verbose	CustomFunctions	[Installation] [Functions] [Begin] Solution=3212b54a-8567-4afe-8037-97a17bf2a762, Workbook=excel add-in 3212b54a-8567-4afe-8037-97a17bf2a762 (version 1).xlsb		
06/06/2019 14:22:30	Verbose	CustomFunctions	[Registration] [Begin] Function=CONTOSO.ADD, Workbook=excel add-in 3212b54a-8567-4afe-8037-97a17bf2a762 (version 1).xlsb		

```

**Comment by keyur32** [comment]
Hey there, 

Arg, sorry for the issue and thanks for the extra detail in the issue - that helps!

It looks like you're on the right build as we try to detect and register the function. We may need to debug this on our machine locally.  Can you ping me directly: kepatel@microsoft.com and we can setup a call to try to unblock you?

**Comment by datavisiondt** [comment]
Hi,

I was following this Tutorial [(Exel Add-In Tutorial)](https://docs.microsoft.com/en-us/office/dev/add-ins/tutorials/excel-tutorial-create-custom-functions?tabs=excel-windows) and ran into the same issue posted here.

I also tried some functions samples on Script Labs, but when I try to register the sample functions I get the following error:

An unexpected error has occurred.
Error:
{
    "description": "There was an internal error while processing the request.",
    "message": "There was an internal error while processing the request.",
    "name": "RichApi.Error",
    "code": "GeneralException",
    "traceMessages": [],
    "innerError": null,
    "debugInfo": {
        "code": "GeneralException",
        "message": "There was an internal error while processing the request.",
        "errorLocation": "CustomFunctionManager.register",
        "statement": "v.register(...);",
        "surroundingStatements": [
            "var workbook=context.workbook;",
            "var v=Microsoft.ExcelServices.CustomFunctionManager.newObject();",
            "// >>>>>",
            "v.register(...);",
            "// <<<<<"
        ],
        "fullStatements": [
            "Please enable config.extendedErrorLogging to see full statements."
        ]
    },
    "stack": "GeneralException: There was an internal error while processing the request.\n   at Anonymous function (https://appsforoffice.microsoft.com/lib/beta/hosted/excel-win32-16.01.js:24:274160)\n   at o (https://script-lab.azureedge.net/static/js/2.1a40d5ab.chunk.js:1:3080955)\n   at Anonymous function (https://script-lab.azureedge.net/static/js/2.1a40d5ab.chunk.js:1:3081102)\n   at c (https://script-lab.azureedge.net/static/js/2.1a40d5ab.chunk.js:1:2401917)"
}

**Comment by dzwillia** [comment]
Hi there, @keyur32!

We're running into the same issue.

We've got a couple of developers working on this as well. As we've been testing this functionality, for those of us that have developed the custom functions add-in and have sideloaded it into Excel, they show up in the formula autocomplete in Excel for Windows (Version 1907, Build 11807.20000), but for those that did not sideload the add-in and installed it via "Admin-Managed", they don't show up in the formula autocomplete.

**Environment**

* Platform: PC Desktop
* Host: Excel
* Office version number: Microsoft Excel 2019 MSO (16.0.11807.20000) 64-bit; Version 1907 (Build 11807.20000 Click-to-Run)
* Operating System: Windows 10

**Comment by keyur32** [comment]
Hey there!

Per our email thread, sharing this for others:

 I think this is because you are on the “Excel 2019 standalone” version. It needs to be office 365.

To build custom functions you can get a free Office 365 developer tenant by joining our developer program: https://aka.ms/o365devprogram

We will follow up to see if we can provide more clear error messages on the versions this is not supported (ie 2019). Thanks!

Get Outlook for iOS<https://aka.ms/o0ukef>
________________________________

**Comment by datavisiondt** [comment]
> Hey there! Per our email thread, sharing this for others: I think this is because you are on the “Excel 2019 standalone” version. It needs to be office 365. To build custom functions you can get a free Office 365 developer tenant by joining our developer program: https://aka.ms/o365devprogram We will follow up to see if we can provide more clear error messages on the versions this is not supported (ie 2019). Thanks! Get Outlook for iOS<https://aka.ms/o0ukef>
> […](#)
> ________________________________ From: Dave Williams <notifications@github.com> Sent: Thursday, June 13, 2019 7:12:28 AM To: OfficeDev/Excel-Custom-Functions Cc: Keyur Patel; Mention Subject: Re: [OfficeDev/Excel-Custom-Functions] Excel: Sample custom functions fail to install; #NAME? when using custom functions (#158) Hi there, @keyur32<https://nam06.safelinks.protection.outlook.com/?url=https%3A%2F%2Fgithub.com%2Fkeyur32&data=02%7C01%7Ckepatel%40microsoft.com%7C2385a833464f435d770508d6f0092b31%7C72f988bf86f141af91ab2d7cd011db47%7C1%7C0%7C636960319506693539&sdata=jmq5qKn2iYGQJOhpbAIBJBHZ1J4KIWk7GbZQgIH9p28%3D&reserved=0>! We're running into the same issue. We've got a couple of developers working on this as well. As we've been testing this functionality, for those of us that have developed the custom functions add-in and have sideloaded it into Excel, they show up in the formula autocomplete in Excel for Windows (Version 1907, Build 11807.20000), but for those that did not sideload the add-in and installed it via "Admin-Managed", they don't show up in the formula autocomplete. Environment * Platform: PC Desktop * Host: Excel * Office version number: Microsoft Excel 2019 MSO (16.0.11807.20000) 64-bit; Version 1907 (Build 11807.20000 Click-to-Run) * Operating System: Windows 10 — You are receiving this because you were mentioned. Reply to this email directly, view it on GitHub<https://nam06.safelinks.protection.outlook.com/?url=https%3A%2F%2Fgithub.com%2FOfficeDev%2FExcel-Custom-Functions%2Fissues%2F158%3Femail_source%3Dnotifications%26email_token%3DAA2QU5YJCHOCRBL3EYNAK7TP2JIUZA5CNFSM4HVCVUXKYY3PNVWWK3TUL52HS4DFVREXG43VMVBW63LNMVXHJKTDN5WW2ZLOORPWSZGODXT2JZY%23issuecomment-501720295&data=02%7C01%7Ckepatel%40microsoft.com%7C2385a833464f435d770508d6f0092b31%7C72f988bf86f141af91ab2d7cd011db47%7C1%7C0%7C636960319506703531&sdata=BpvXYB2BiVHShz3Vd4cAjV0ekLx%2F1n5tz4qvv%2BOw%2FOQ%3D&reserved=0>, or mute the thread<https://nam06.safelinks.protection.outlook.com/?url=https%3A%2F%2Fgithub.com%2Fnotifications%2Funsubscribe-auth%2FAA2QU57V666GOQ6PDQQDUNLP2JIUZANCNFSM4HVCVUXA&data=02%7C01%7Ckepatel%40microsoft.com%7C2385a833464f435d770508d6f0092b31%7C72f988bf86f141af91ab2d7cd011db47%7C1%7C0%7C636960319506713535&sdata=izOLhLdeWpwQB18accJBkQGVN2E3Y1NGPQQt72HY10A%3D&reserved=0>.

@keyur32  This is the version we get on MSDN Enterprise for development testing.  Is MSDN allowing us to use a subscription version of Office 365 for development/testing now?

**Comment by jeffj** [comment]
@keyur32 Will this "office 365 requirement "be an Issue with this feature is in production?  I need my Add-in to support stand alone versions when this leaves the sandbox.

**Comment by jeffj** [comment]
@keyur32 Additionally the best place to tell Developers out breaking issues related to new features is in the [Getting Started.](https://docs.microsoft.com/en-us/office/dev/add-ins/quickstarts/excel-custom-functions-quickstart?tabs=excel-windows).

Might want to mention stand alone as a no no.

**Comment by keyur32** [comment]
@datavisiondt  - I believe the MSDN Enterprise (now I think called Visual Studio subscription) should give you access to Office 2019 AND Office 365. 

![image](https://user-images.githubusercontent.com/3476087/59614588-ea02da00-90d5-11e9-9c78-00db44b39b9a.png)



@jeffj - Yes, currently this will only work on Office 365. It will not appear in the store dialog for non Office 365 versions of Excel. 

Good suggestion, we'll make it more clear within our documentation (@mscharlock was working on that)!  Also, if you have additional feedback, @kbrandl is working on a plan to aid with discovery.

**Comment by datavisiondt** [comment]
> @datavisiondt - I believe the MSDN Enterprise (now I think called Visual Studio subscription) should give you access to Office 2019 AND Office 365.
> 
> ![image](https://user-images.githubusercontent.com/3476087/59614588-ea02da00-90d5-11e9-9c78-00db44b39b9a.png)

@keyur32.  Visual Studio Subscription does have an Office 365 and Office Stand Alone version, but only the 90 days or X days Dev Subscription you are pointing out in the screen shot works because it offers a E3 version.  The other versions available on VS Enterprise Subscription Download have the same limitation.  We have 3 options, but it is important to point out to developers that only the 0365 Dev Subscription will allow us to develop the new Javascripts Add-In custom functions.   I also found out that it also works on my personal O365 Home Premium subscription.

**Comment by keyur32** [comment]
Thanks! Good point, to clarify we work on all versions of "Office 365".  

Custom Functions and new Excel AP requirement sets like 1.9 are not supported in Excel 2019. This will also be consistent with other features like Excel Dynamic Arrays which will only be available through Office 365.  

I've logged this issue on our docs repro to track the documentation fix: https://github.com/OfficeDev/office-js-docs-pr/issues/1092

**Comment by keyur32** [comment]
Marking this as closed with the note as this was addressed 9 dates ago.  thanks @mscharlock 

Apolgoes, @datavisiondt  - didnt get back to your question directly - Yes, if you have a VS Enterprise Subscription, I'd recommend that as that subscription I believe will automatically renew, vs the Office 365 Developer tenant which auto-renews based on developer activity.
