### ISSUE TITLE
Authenticated API calls from Custom Function?

### ISSUE THREAD

**Issue by andrewbridge** [OfficeDev/Excel-Custom-Functions#160]
I'm currently looking to build an integration with an API that uses a JWT token for authentication.

I'm just looking to pull data with GET calls with 

```
Authorization: 'Bearer ...jwt'
```

as a header.

Based on the ["Receive and handle data with custom functions"](https://docs.microsoft.com/en-us/office/dev/add-ins/excel/custom-functions-web-reqs) page in the documentation, it looks as though the set of headers and content types is a small subset of headers which does not include the `Authorization` header.

Does this restriction mean access to this type of authenticated API is not possible?

The `fetch` request I'm making is to an API I'm currently hosting locally for development. It's running on localhost on an alternative port. The `fetch` request fails with an error `Network Request failed` suggesting the request was never made due to a CORS issue or something similar. The page I linked above also suggests a same origin policy is in place, would this be blocking the request?

```js
/*
Assuming:
endpoint = "Valid/Api/Endpoint";
accessToken = "Bearer eyJhbGciOiJSUzI1N...";
*/
fetch(
    `https://localhost:8081/api/${endpoint}`,
    {
      mode: "cors",
      headers: {
        Authorization: accessToken
      }
    }
  ).then(r => {
    return r.json()
  }, r => {
    // r is a TypeError detailed below
  });
```

```json
{
    "message": "Network request failed",
    "stack": "stack:TypeError: Network request failed\n   at o.onerror (foundation.win32.bundle:1:123697)\n   at dispatchEvent.value (foundation.win32.bundle:1:36516)\n   at value (foundation.win32.bundle:1:111669)\n   at value (foundation.win32.bundle:1:108416)\n   at Anonymous function (foundation.win32.bundle:1:110776)\n   at value (foundation.win32.bundle:1:61902)\n   at value (foundation.win32.bundle:1:56068)\n   at Anonymous function (foundation.win32.bundle:1:53578)\n   at value (foundation.win32.bundle:1:55337)\n   at value (foundation.win32.bundle:1:53547)"
}
```

Let me know if I can provide any further information.

**Comment by 289abhi** [comment]
The origin is calculated as scheme+ domain+ port. If you have the JavaScript file hosted on the same origin then the Same Origin Policy will be applied which should allow the custom headers (e.g. "Authorization" header). If the file is on a different origin (could be a different port on same domain), then the "simple CORS" policy a.k.a. "simple request" is applied, which only allows standard headers and 3 verbs - GET,HEAD,POST.

I hope this is useful. Let us know if you have any further questions.

**Comment by kbrandl** [comment]
@andrewbridge I'm going to go ahead and close this issue, since a response has been provided. Please comment again here if you need further info and we'll reopen this issue. Thanks!

**Comment by adammpolak** [comment]
@289abhi @kbrandl 

Does this mean I cannot make an authenticated POST request to an outside service in a custom function?

**Comment by adammpolak** [comment]
@289abhi  @kbrandl following up ^

**Comment by kbrandl** [comment]
@adammpolak I'm no longer part of the Microsoft team, so am unfortunately not able to help with this. @keyur32 can you assist or redirect this inquiry to someone who can? Thanks!
