### ISSUE TITLE
Integrate custom functions in an existing excel add-in

### ISSUE THREAD

**Issue by jjtfsalgado** [OfficeDev/Excel-Custom-Functions#17]
I have an existing excel add-in developed with the js API that inserts a task pane and I wonder if it is possible to add custom functions to it? It seems that the manifest doens't support this kind of integration.

**Comment by Rick-Kirkham** [comment]
It is possible. You can add a ExtensionPoint of type CustomFunctions to the manifest of an existing add-in.

**Comment by jjtfsalgado** [comment]
Thank you @Rick-Kirkham. I did that already but I sill didn't managed to load the custom functions. The other task pane add-in its working fine, but the custom functions don't appear. And when I load the add-ins in separate they work just fine.

I added the custom functions extension point, added the custom functions bit to the resources Urls and ShortStrings and replaced the html source location of the cf to be the task pane html. 

Here is my manifest:
[manifest.txt](https://github.com/OfficeDev/Excel-Custom-Functions/files/2110806/manifest.txt)

And this is a snippet of the html page of the two add-ins:
![html](https://user-images.githubusercontent.com/14180997/41529980-a4d651f4-72e6-11e8-9844-e7be3a5a3f38.PNG)

**Comment by Rick-Kirkham** [comment]
@jjtfsalgado Since your problem is with your own add-in with custom functions, its not really an issue with the sample in this repo. Please raise your issue on StackOverflow and tag it "office-js". It will be seen by more experts and the answers that you get will be available to the whole community. Thanks.
