### ISSUE TITLE
Use object EXCEL into custom function

### ISSUE THREAD

**Issue by macahrtur** [OfficeDev/Excel-Custom-Functions#175]
Hello,

I'm trying use the next code into a custom function but I have getted a error:

"Excel is not defined" 

could please help me?

/**
 * Get data.
 * @customfunction 
 * @param entity First entity
 * @param {number[][]} columns list of columns
 * @param {string[][]} codes list of columns
 * @param startdate First entity
 * @param enddate First entity
 * @param operation First entity
 * @returns The sum of the two numbers.
 */
function getData(entity: string, columns: number[][], codes: string[][], startdate: string, enddate:string, operation:string): string {
    try {
      Excel.run(async context => {
        /**
         * Insert your Excel code here
         */
        const range = context.workbook.getSelectedRange();
  
        // Read the range address
        range.load("address");
  
        // Update the fill color
        range.format.fill.color = "yellow";
  
        context.sync();
        return "12";
      });
    } catch (error) {
      return error.message;
    }

  }
}

**Comment by akrantz** [comment]
You cannot use Office.js within a custom function. Make the custom function take a parameter, and pass the value when the function is called. For example, function add(first: number, second: number) { return first + second; }  is called with =ADD(1, 2).

**Comment by davidchesnut** [comment]
Hi @macahrtur it looks like @akrantz answered this issue. I'm going to close this issue, but please reopen if you have any additional questions. Thanks!

**Comment by rocknet** [comment]
@davidchesnut Just to clarify this, is there no possible way to pass a cell reference as a parameter to a custom function and operate on the value of the cell?  For instance, if A1 contains -1, you can use =ABS(A1) to get the value 1, is this not possible currently with custom functions?  If it's not, is it on the roadmap?  This is pretty key for some of our use cases.
