### ISSUE TITLE
custom functions cannot retrieve data within Windows Office, but works fine on Mac Office

### ISSUE THREAD

**Issue by jackarcher73** [OfficeDev/Excel-Custom-Functions#176]
*** NOTE: If you have an issue running your custom function, please log an issue in the official office-js repo here: [https://github.com/OfficeDev/office-js/issues](https://github.com/OfficeDev/office-js/issues) ***

In our custom function we want to retrieve data by POST method from our API. The code is as below. It works perfectly in Mac Excel, but never works in Windows Office 365. What I am missing?

const xhttp = new XMLHttpRequest();
xhttp.onreadystatechange = function() {
  if (xhttp.readyState !== 4) return;
  ... ...
};

xhttp.open("POST", '/hdb/batchFunction', true);
xhttp.setRequestHeader("Content-Type", "text/plain");
xhttp.send(JSON.stringify(requestBatch));

**Comment by lliu113** [comment]
Hi @jackarcher73, thank you for the question! Looping in @keyur32 to provide more guidance

**Comment by jackarcher73** [comment]
Any progress?
I added some log entry:
8/29/2019 23:17:03	Verbose	Runtime	[Console] [Log] before new XMLHttpRequest		
8/29/2019 23:17:03	Verbose	Runtime	[Console] [Log] before open		
8/29/2019 23:17:03	Verbose	Runtime	[Console] [Log] xhttp.readyState=1		
8/29/2019 23:17:03	Verbose	Runtime	[Console] [Log] before setRequestHeader		
8/29/2019 23:17:03	Verbose	Runtime	[Console] [Log] before send		
8/29/2019 23:17:45	Verbose	Runtime	[Console] [Log] xhttp.readyState=4		
8/29/2019 23:17:45	Verbose	Runtime	[Console] [Log] xhttp.status=0		
8/29/2019 23:17:45	Verbose	Runtime	[Console] [Log] Unexpected CustomFunctions [Execution] [End] [Failure] [RejectedPromise] Function=GET_CUBE_DATA Error: Error code = 15
 {}

**Comment by lindalu-MSFT** [comment]
@keyur32 Have you had a chance to look at this one?

**Comment by keyur32** [comment]
Hi @jackarcher73 , super sorry for the delay. My notificatiosn went to junk somehow.

I think the issue you may be hitting is on Windows, there needs to a be a local host execption granted via fiddler so the Windows sandbox can post back to your process.

**Comment by keyur32** [comment]
Here is the guidence we have on that: https://docs.microsoft.com/en-us/office/dev/add-ins/excel/custom-functions-troubleshooting#cant-open-add-in-from-localhost-use-a-local-loopback-exception.    Please let us know if that doesn't work, closing for now. Thanks!
