### ISSUE TITLE
How can an excel custom function return data in range or set values for a range of cells?

### ISSUE THREAD

**Issue by topkoong** [OfficeDev/Excel-Custom-Functions#177]
I was trying to follow the sample code below but no luck. When I called the function below, I got only 1 for a single cell. Therefore, I was wondering if you guys can show me examples which can set values for a range of cells or set range by address.

Thank you!

```
/**
 * Returns matrix
 * @customfunction
 * @returns {number[][]} Returns a range of cell data as a two-dimensional array
 */
function returnMatrix() {
  return [[1,2,3,4], [1,2,3,4], [1,2,3,4]];
}
```

**Comment by akrantz** [comment]
Dynamic Arrays are a new feature. If the feature is not available, it will only show the value for the first cell.

This blog post metioned that it is available for Insiders: https://blog-insider.office.com/2019/06/13/dynamic-arrays-and-new-functions-in-excel/

This is subject to change as the feature is rolled out. 

@keyur32 could you provide more information about availability?

**Comment by topkoong** [comment]
@akrantz I have a few questions regarding this.

1. Can I set range by address or are there any alternative ways which I could return multiple values, multiple grids? 

2. I know that task pane, content add-in, and commands run in a browser engine runtime, and the browser engine runtime supports the Office.js APIs, which allow me to manipulate Excel tables. However, any of the Excel APIs aren't directly accessible from the custom functions runtime. So, I was wondering if there is any workaroud for utilizing Excel JavaScript API.

3. Why does excel custom functions attempt to make a GET request to the following URL: https://excel.officeapps.live.com/x/_vti_bin/DynamicGridContent.json/GetRangeContent?context=% from Aacorlib_new.min.js all the time?

4. What does a OsfRuntimeExcelWac.js file do exactly?

I'm trying to Custom functions architecture from https://docs.microsoft.com/en-us/office/dev/add-ins/excel/custom-functions-architecture, yet the details won't suffice.

I was wondering if you could help me out! 

Thank you for your time and consideration!

**Comment by keyur32** [comment]
For number 1, you could set an interval and do the write after Excel has returned on the onCalculated Event. It will require the taskpane to be visible currently.

2. This one is on the backlog, hope to have something in preview soon.

3/4 - are internal files needed for the runtime. thanks!

**Comment by topkoong** [comment]
@keyur32 Thank you for the reply! Can you elaborate more or show sample code for the first question?

Thanks!

**Comment by topkoong** [comment]
@keyur32  I found your Script lab gist given below, which is pretty similar to what you told me. However, it seems like I have to work with the taskpane to make it work.
https://gist.github.com/keyur32/ddebdb0e8ae2f6867f605a8309670dc3

**Comment by keyur32** [comment]
Hi, yes your are right in you would need the taskpane to be visible in this case. We have a mode coming soon where this won’t have to be visible any longer.

**Comment by topkoong** [comment]
@keyur32  Thank you for the reply. When will this thing and dynamic arrays be released to an online version of Microsoft Excel?

**Comment by pasdechancee** [comment]
Hi, i'm interested by this issue as well. I have a (maybe naive) question : would it be possible tout use CTRL SHIFT ENTER (CSE) formulas ? If so, what should the JavaScript fonction return ? Thanks !

**Comment by keyur32** [comment]
Hi @topkoong , still in preview but team is working on it.   @pasdechancee , yes you can.  You simply just return a 2d array, i.e.  return [[1,2],[3,4]]  would make a 2x2.  If it is not CSE entered, then Excel will show the top left item. 

I'd recommend keeping up on our blog on https://developer.microsoft.com/office or in our monthly community call https://aka.ms/officeaddinscommunitycall. 

Closing this for now. Stay tuned!

**Comment by topkoong** [comment]
@keyur32  When will this feature be available for installed Excel version? Looks like it is only available for Excel web version.

**Comment by sprai93** [comment]
Hi @keyur32  why "/x/_vti_bin/DynamicGridContent.json/GetRangeContent?context" will throw 500 error? 
Is there any particular reason for this error?

Below is the URL pattern which is resulting 500

/x/_vti_bin/DynamicGridContent.json/GetRangeContent?context={"WorkbookMetadataParameter":{"WorkbookMetadataState":{"MetadataVersion":0,"ServerEventVersion":0}},"SessionId":"32.a151ece71b214854b5348b44092f7d2e1.D60.1.V24.58251wi7F3zeuw7tIbazNCRn14.5.en-US5.en-US5.admin1.S1.N14.16.0.8471.857314.5.en-US5.en-US1.V1.N0.1.S","TransientEditSessionToken":null,"PermissionFlags":786361,"Configurations":1577728,"CompleteResponseTimeout":0,"CollaborationParameter":{},"MachineCluster":"","AjaxOptions":0}&ewaControlId="m_excelWebRenderer_ewaCtl_m_ewa"¤tObject="PBDP Operational EBITDA"&namedObjectViewData={"Mode":1,"Settings":2}&row=28&column=30&rowCount=28&columnCount=30&blockPosition={"X":1,"Y":1,"PaneType":1}&revision=0&previousRevision=-1&digest=null&renderingOptions=0&colorScheme=null&_sm_byp=iVVnjnZs7qRf16nR
