### ISSUE TITLE
Question: Custom Function w/o a Namespace

### ISSUE THREAD

**Issue by dbettin** [OfficeDev/Excel-Custom-Functions#189]
We are looking at porting over our current Excel add-in (Excel-DNA) to the JS model.  Is it possible to have a custom function without a namespace?  To be specific our current function is named `tagnifi` and we must keep this name for backward compatibility.

**Comment by mscharlock** [comment]
@RuoyingLiang do you mind checking into this? If I remember correctly from writing some of the custom functions documentation, a namespace is required but I would like @RuoyingLiang to confirm. Thanks for your patience on this issue!

**Comment by dbettin** [comment]
If this is true, is this paradigm only intended for new add-ins (as opposed to ports)?

**Comment by mscharlock** [comment]
Tagging @keyur32, would you mind giving some input? Thanks!

**Comment by mscharlock** [comment]
Hi @dbettin - Just had a chat with @keyur32 and namespace is optional. 
I'm going to close this issue for now, but comment on this thread if you need more assistance or have other questions and I am happy to reopen. Thanks!

**Comment by dbettin** [comment]
Thanks! Could you please point to the documentation that describes how to add a function without namespace?

**Comment by mscharlock** [comment]
This is actually an issue in our docs, as we have namespace listed in our reference docs as being required. I'm putting an item on our backlog to make sure this gets updated properly. However, to make one without a namespace, just eliminate the namespace in your add-in's manifest file. More docs on that namespace element here: https://docs.microsoft.com/en-us/office/dev/add-ins/reference/manifest/namespace. Hope that helps, let me know if you still need help.

**Comment by akrantz** [comment]
I think the point is more nuanced than that. If there is a need for XLL compatibility, then you can have an empty namespace in the manifest and you can use the compatible name. But the recommendation is to use a namespace to avoid collisions, or if the manifest has an empty namespace, use a naming convention with a prefix such that it is equivalent to a namespace e.g. "namespace.function".   @keyur32 Please confirm this, but this is my recollection.

**Comment by keyur32** [comment]
@akrantz, XLL Compatability mode doesn't use the namespace attribution (as this capability didn't existi).  I believe the documentation issue is also fixed, so closing.
