### ISSUE TITLE
Questions on future plans

### ISSUE THREAD

**Issue by doria90** [OfficeDev/Excel-Custom-Functions#19]
Hey Guys,
This is more of a question than an issue:
How is this going to be implemented in future builds?
I'm guessing side-loading add-ins won't happen with day-to-day users so, is there a plan to embed JavaScript code within Excel files OR will JavaScript in Excel will always be through add-ins?

I am eager to hear your response.
Thanks,
Amit.

**Comment by keyur32** [comment]
Hi @doria90,  in terms of custom functions, these are meant to be additional capabilities for existing add-ins, and in general will follow that model for acquiring them and updating them. Whenever a workbook is shared across users, the recieving user will be prompted to enable the add-in to continue using these functions.

There is one caveat that Excel desktop will maintain a cache of these for performance reasons. You can see this cache today in the following folder: '<username>\AppData\Local\Microsoft\Office\16.0\Wef'

**Comment by keyur32** [comment]
Marking this issue as closed. Let me know if you have additional questions. thanks.
