### ISSUE TITLE
Format custom function cell

### ISSUE THREAD

**Issue by andrewkittredge** [OfficeDev/Excel-Custom-Functions#191]
Is it possible to format the cell from which a custom function was called?

I have the address via the `invocation` parameter I need access to the `workbook`, which I do not think I have in the custom function runtime.  

Is there any easy way to do this?

**Comment by keyur32** [comment]
@andrewkittredge  -  This repro is about the code sample itself not about the feature, and is looked at on a slower cadence.  (Don't worry we'll transfer it over to the right repo).

For your answer, logging the same response as we made on the community call:
"we're working on a way to return formatted information but is on the backlog. Today, you can look at passing some context from the custom function to the the taskpane and then "stamping" it via office.js.  Check out this tutorial: https://docs.microsoft.com/en-us/office/dev/add-ins/tutorials/share-data-and-events-between-custom-functions-and-the-task-pane-tutorial"

**Comment by andrewkittredge** [comment]
An example of how to do this would be very helpful.  I hacked a message bus with the Shared Storage but I cannot find a place where I can listen on the bus and have access to the Excel object to modify the cells.

**Comment by keyur32** [comment]
Hey Andrew, here is the custom function call: https://docs.microsoft.com/en-us/office/dev/add-ins/excel/configure-your-add-in-to-use-a-shared-runtime.  

To describe in detail:
- In your custom function, use the caller.address property and save that to some global state (i.e. Format A1's result with the $)
- In your oncalculatedevent which will fire only after the functions have finished calculating, query that global state and perform that action.

Hope that helps unblock you for now, until we build it directly as part of the return value. An Example of how this will work by looking at the STOCKHISTORY() function that is built in and currently rolling out to Insiders and returns formatted values. Once that feature is stabilized, we'll be looking at extending it for 3rd parties.  Thanks!

**Comment by druidsbane** [comment]
@keyur32 is there any update or sample documentation on how we can implement this today without callbacks and just return formatted cells?

**Comment by keyur32** [comment]
@grangeryy can highlight this using both the callerAddress properties, and the onCalculate event. We'll be working on allowing you to return formatted number values directly from your function.
