### ISSUE TITLE
Infrastracture question that I couldn't get anwser from Excel addin documentation

### ISSUE THREAD

**Issue by lukchen** [OfficeDev/Excel-Custom-Functions#194]
Hello,

1.  According to this page: [https://docs.microsoft.com/en-us/office/dev/add-ins/tutorials/share-data-and-events-between-custom-functions-and-the-task-pane-tutorial](url) 
first paragraph it says "Excel custom functions and the task pane share global data, and can make function calls into each other". How can taskPane js and custom function js call each other since they are not in same runtime? I only know they can share data through Runtime storage

2.  [https://docs.microsoft.com/en-us/office/dev/add-ins/excel/make-custom-functions-compatible-with-xll-udf](url) 
It says using an equivalent XLL can make Excel using XLL functions instead of javascript custom functions. what is the detailed way for identifying the equivalent XLL? I mean by the file names or the functions that inside XLL? If it's second one, i have 2 same function in both existing XLL and javascript custom functions, after I specifed XLL in manifest, is it supposed to be the XLL function would be used over the javascript function? And what's the rule to identify if the functions are equivalent(name, parameter, return type etc)?

3.  Can I call XLL functions from addin UI side? such like from TaskPane, Dialog or ContentPane?
    Can reflect XLL function results on UI?

Thanks

**Comment by mscharlock** [comment]
Hi @lukchen - Sharing data between the taskpane and custom functions has recently changed, as in this feature the taskpane and custom functions can share a runtime. This feature is in public preview and only available on Excel for Windows. Custom functions' runtime `storage` will still be available and not deprecated so if you have an existing add-in using the two runtime system, it will still work. However, if you are building an add-in from scratch right now, I would advise you use this new model as described in the tutorial. 
I will let @RuoyingLiang answer your questions about XLLs.

**Comment by lukchen** [comment]
Thanks for the quick reply! @mscharlock 
" I would advise you use this new model as described in the tutorial."
Are you refering to the purple Note area of this page: [https://docs.microsoft.com/en-us/office/dev/add-ins/tutorials/share-data-and-events-between-custom-functions-and-the-task-pane-tutorial](url)? I checked my Excel there is no Insider option...My organization using office 365

**Comment by lukchen** [comment]
Hello @RuoyingLiang ,

Just want to check in if you are aware of the question. 

Thank you!

**Comment by mscharlock** [comment]
@lukchen Yes, the purple note area is what I'm referring to. It sounds like you may have to ask your Office 365 admin to get Office Insider so you can use this feature. There should be more details here: https://insider.office.com/en-us/business. But, that's definitely why this isn't working for you.

**Comment by lukchen** [comment]
Since the latest design that add in UI javascript can call js custom function now. What will happen when there is a equivalent XLL custom function?

**Comment by lukchen** [comment]
I cannnot even make XLL function over the js custom function after specifying the equivalent XLL in manifest
For example, I have a XLL function Reverse(input) that reverse a string and return it. In js cunstom function I have a same name function Reverse(input) which is a fake function returns something else:

![image](https://user-images.githubusercontent.com/26646767/73671586-3a38a780-4679-11ea-8da3-4554c9b455fd.png)

After build and run, I can see 2 same name functions from sheet:

![image](https://user-images.githubusercontent.com/26646767/73671396-dc0bc480-4678-11ea-8a31-2d5df4c63422.png)

Tabbing on each of them shows all function description from XLL and js custom function.
But when using them they are all actually the js custom function that returns fake result.

The XLL function cannot be called in this case

**Comment by RuoyingLiang** [comment]
@lukchen the function name is used to match the XLL and JS custom function. In the above case, the XLL should be used in Win32. Could you share the manifest with us so we can investigate what's the problem?

**Comment by lukchen** [comment]
> @lukchen the function name is used to match the XLL and JS custom function. In the above case, the XLL should be used in Win32. Could you share the manifest with us so we can investigate what's the problem?

Is the XLL--js custiom function compatibility only works in Win32? My machine is 64 bit Windows, also my Excel & XLL is 64 bit version. 

I think my question is, is it possible to call XLL not from sheet but from addIn ui javascript? Since the Insider has preview feature that the addIn ui javascript can call the js custom function now.
So I'm wondering, if there is a XLL matching the js custom function, when the addIn ui js call js custom funcion, finally the XLL function would be called, thus the addIn ui js can call XLL function mediately, is it possible?

mediate |  
-- | --

**Comment by RuoyingLiang** [comment]
DIscussed in mail thread. the add-in's XLL compat works now. 
For the 3rd question, XLL cannot be called from JS add-in UI.
