### ISSUE TITLE
Custom Functions add-in without task pane opening?

### ISSUE THREAD

**Issue by rocknet** [OfficeDev/Excel-Custom-Functions#195]
We don't really see a need for the task pane being open when using our functions, which primarily are getting data from another system.  Is it possible to configure the manifest such that the task pane doesn't open?

**Comment by mscharlock** [comment]
Yes! I believe if you are an Office Insider this behavior is already available via the latest January fork, but not yet documented. I am hoping to finish the docs on it this week. Hope that helps. I can update this issue when the docs are in place.

**Comment by mscharlock** [comment]
So we are currently updating this feature but the timeline has changed and anticipate that everything should be up and running by beginning of March. If there is an update sooner than that, I will let you know! :)

**Comment by keyur32** [comment]
Hi @rocknet 

We announced the preview of a shared runtime a week ago and this may be of use for you: https://docs.microsoft.com/en-us/office/dev/add-ins/excel/custom-functions-shared-overview.

This will allow you greater flexibility when creating custom functions, as it unblocks full CORS, calling libraries and much more. Optionally, if you wanted not to use a shared runtime, you can do that as well.

Even with this, you *can* create an add-in without a taskpane and only custom function, especially if you plan to deploy these in house.  However, if you wish to publish the add-in to the store, it should contain an add-in command. That command can show a dialog/taskpane but it should indicate to users how to use the add-in and custom functions.  Add-ins with only custom functions are not allowed in the store, as their wouldn't be a good mechanism for end users to manage or discover your add-in capabilities.

Hope that makes sense.  Also, this seems like a great question for StackOverflow.  Can you log it there and we can also respond.

**Comment by keyur32** [comment]
Hi there, closing this issue as Shared Runtime is now generally available and has not been updated. Please reactivate if this is remains unresolved.
