### ISSUE TITLE
OfficeJS: How to show Custom Error Messages in Excel add-in instead of "#BUSY"

### ISSUE THREAD

**Issue by Murugananths** [OfficeDev/Excel-Custom-Functions#198]
Hi Team,

Kindly help on below scenario:
Existing system : In Excel add-in when using Custom functions the API response values binded with message showing as "#BUSY" in excel cells.

Proposed system:  As per requirement , have to customize the message to show "Calculating" in excel cells when invoking custom functions.

**Comment by shyambhiogade** [comment]
I am also facing the same problem, @TCourtneyOwen @RuoyingLiang @georgek01 @Reezaali can you please help on this.

**Comment by csreddyennam** [comment]
I too face similar issue, please help us

**Comment by Murugananths** [comment]
> Hi Team,
> 
> Kindly help on below scenario:
> Existing system : In Excel add-in when using Custom functions the API response values binded with message showing as "#BUSY" in excel cells.
> 
> Proposed system: As per requirement , have to customize the message to show "Calculating" in excel cells when invoking custom functions.

Hi Team any update  please....

**Comment by Murugananths** [comment]
Not sure why no response even so many uservoice....

**Comment by RuoyingLiang** [comment]
Sorry for the late response. @Murugananths do you mean you want to show"calculating" instead of "#Busy" during custom function execution? As many custom function didn't really calculate but executing service call or others, "busy" is more accurate for most case. Could you share more context with us why this is an issue in your scenario? That will greatly help us triage. Thanks.

**Comment by Murugananths** [comment]
Thanks for the response Ruoying. Below are the context we require.

1) This is as per customers requirement,,
2) Already other Excel application implemented with same,
3) Also since these are involved with calculations hence finding meaningful name...

**Comment by RuoyingLiang** [comment]
Let me confirm to make sure if I understand correct:  you mean your add-in's customers asking for not showing "#Busy"? 
And could you let me know what's the other Excel application you refereed?

**Comment by Murugananths** [comment]
I mean already other application which was developed in .net using ExcelDNA showing message as "#Calculating" when invoking custom functions. Hence same we are trying to  implement.

**Comment by RuoyingLiang** [comment]
Got it. Thanks for the explanation. I will definitely add this request to out backlog. But currently custom function doesn't support customize the message during execution. Sorry for the inconvenient. One more question: is "#busy" make confusing in your add-in so you want to show "#calculating" or you need to show "#calculating" to keep consistent with previous experience?

**Comment by akrantz** [comment]
Would it be better for the `#Calculating` string to also be changed to `#Busy` so they match? It sounds like the consistency between the two is more important than being able to customize the string.

**Comment by Murugananths** [comment]
@RuoyingLiang ...For below reasons.
1) "#calculating" to keep consistent with previous experience
2) It will make confusing for the customers who had already experienced...

**Comment by Murugananths** [comment]
Any tentative release dates as most user requesting the same features....

**Comment by keyur32** [comment]
Hi there, I can comment on the design. We went with the smallest string as possible to avoid having to adjust column widths, and knowing that in certain locales that would be localized further. It isn't possible to localize the string.

What you could do is use a streaming function, with your intermediate state being your custom message. This would still show #busy on first invocation, but would be the string you set afterwards.  You would set the string right away, and set a timeout interval, on that interval you would need to return the result and then cancel the interval.

Also, for future feature requests, please post those on the uservoice site at officespdev.uservoice.com.  Hope that helps and thank you for the feedback and discussion.
