### ISSUE TITLE
Custom functions not working for Azure hosted Office Excel add-in

### ISSUE THREAD

**Issue by dabbara-geetha** [OfficeDev/Excel-Custom-Functions#200]
Hi,

I've created an excel add-in custom function using Yo generator.

I've hosted the custom functions excel add-in dist folder to the Azure app service, added web.config as well and updated website URL in the manifest(XML) file.  I am able to access all the hosted files from the website link. 
After uploading the manifest to excel online, custom functions are not working but task pane is showing.
I tried hosting the same build(dist folder) to GitHub, the custom functions are working with Github URL
Is there any problem with azure hosting? please suggest.
Below is the Azure web.config setting
![image](https://user-images.githubusercontent.com/62707899/78066607-484a3200-7363-11ea-8597-d02647286b63.png)

Thanks in advance

**Comment by ElizabethSamuel-MSFT** [comment]
@dabbara-geetha Sorry to hear you're facing an issue and thanks for letting us know.

@RuoyingLiang Can you take a look?

Thanks.

**Comment by weshi** [comment]
@dabbara-geetha could you check if your web server on the azure websites enabled CORS support? From your description in #193, it seems that your custom functions failed to register, that's why no function intelligence are shown when you try to enter the formula. You should have seen an error message in the Excel status bar saying that there are errors to install the functions.

**Comment by dabbara-geetha** [comment]
@weshi - I've enabled CORS and now I see the custom functions are working in Excel online. 
Thank you for the quick response.

**Comment by dabbara-geetha** [comment]
Excel custom add-in is working fine with Azure & IIS hosting by following below steps
make sure to host the website with HTTPS
enabling CORS & Adding web.config
Make sure the function.js has the hosted website path if fetching any JSON files from dist folder
