### ISSUE TITLE
Excel charts not properly updating after evaluating custom functions

### ISSUE THREAD

**Issue by mmcelligott1** [OfficeDev/Excel-Custom-Functions#203]
Very straightforward to replicate, attaching a video that captures it best:

[Chart Issue.zip](https://github.com/OfficeDev/Excel-Custom-Functions/files/4517508/Chart.Issue.zip)

- Chart some data that relies upon custom function(s)

- Re-evaluate the custom function

- The chart is not updated properly, it seems to always be one step behind for this example

**Comment by vapglobal** [comment]
**A similar/relevant and very destabilizing bug exists in the following scenario when using custom functions outputs for charts and also shapes with text referencing cell values:**

**STEPS TO RECREATE**
1. Create data set with a custom function (ideally a 2d array output but can be anything)
2. Insert a (basic) chart using the data from the output of that custom function
3. Save the file as .xlsx OR save as binary/stringified object using the Excel JS API
4. When a second user opens the sheet OR loads it from a stringified base64 object, Excel throws multiple errors on open referencing broken names, broken links etc as the cause
4a) _"Excel found a problem with one or more formula references in this worksheet.
      "Check that the cell references, range names, defined names, and links to other workbooks in your formulas are all correct"_
5. After clearing the multiple error messages, the ribbon error checking & name manager/formulas show NO errors
6. If excel hasn't crashed, sometimes* user can recover the chart by right clicking into every single data series range reference from "Select data" --> totally random


**STEPS TO RECREATE - CHARTS W/ (DYNAMIC) NAMED RANGES **
1. Create data set with a custom function (ideally a 2d array output but can be anything)
2. Insert a (basic) chart using the data from the output of that custom function
3. Create named or dynamic named ranges for the chart data series that reference cells with output data from the custom functions
4. Save the file as .xlsx OR save as binary/stringified object using the Excel JS API
5. When a second user opens the sheet OR loads/inserts it from a stringified base64 object, Excel throws multiple (violent) errors on open referencing broken names, broken links etc as the cause (see above)
6. **The entire Excel instance crashes 50-75% of the time as a result** resulting in an almost traumatic user experience
7. When able to actually load, the charts will be totally broken UNTIL/UNLESS
    7a) User right clicks chart, chooses select data... goes through every series
    7b) In the defined data ranges for some (random) of the data series the syntax has changed to reference a workbook/worksheet/scoped area that does not exist or belongs to the original source of origin

**EXAMPLE**
    7c) When created and saved the named range looks like (something very similar) this:
          =Book2!cs_price_open

        When open by another user with broken charts it looks like this (with random number)
        =235649152!cs_price_open

@keyur32 or @RuoyingLiang --> **more than happy to show you this in real time if you would like. This is a major and destabilizing issue.**

**Comment by RuoyingLiang** [comment]
@mmcelligott1 for the chart updating issue. The fix has already checked-in. But it haven't rolled out to production yet. We will confirm and back to the thread  once the fix hit the production.

**Comment by RuoyingLiang** [comment]
@vapglobal we are investigating the issue you mentioned. It will be great if we can see the repro in real time to get more info. Could you let me know your email address so I can schedule a Teams call? ( Or you can send mail to me directly. My mail address is ruoyingl@microsoft.com)
