### ISSUE TITLE
Web Assembly Support

### ISSUE THREAD

**Issue by dbettin** [OfficeDev/Excel-Custom-Functions#208]
With the release of Blazor Web Assembly for the web, is there a roadmap for including web assembly support for custom functions?

**Comment by jimmcslim** [comment]
I agree that this would be a game changer.

**Comment by RuoyingLiang** [comment]
Thanks for the suggestion! Could you raise this request in UserVoice [https://officespdev.uservoice.com/forums/224641-feature-requests-and-feedback/filters/top?category_id=163563](url) ? This will help us the prioritize new request.

**Comment by dbettin** [comment]
Already a request here: https://officespdev.uservoice.com/forums/224641-feature-requests-and-feedback/suggestions/39203794-blazor-development-support.  Please upvote if you agree with the request.

**Comment by keyur32** [comment]
Marking this as closed, ssince it is tracked on User voice already. thanks.
