### ISSUE TITLE
Can force return when resolve the result？

### ISSUE THREAD

**Issue by trionfo1993** [OfficeDev/Excel-Custom-Functions#21]
My customer function link to my company's database and which i get can be string or number,  they want number can be formatted, but in json, i can only design 1 type.

```
function BASIC(Ticker) {
    // 请求数据配置
    var url = ""
    url = url + Ticker);

    return new OfficeExtension.Promise(function (resolve) {
        axios.get(url)
            .then(function (response) {
                return response.data
            })
            .then(function (json) {
                // result can be 'can not find ticker' or a number like 9.99
                var result = json["data"]
                resolve(result)
            })
            .catch(function (e) {
                resolve(e.message)
            })
    });
}
```

**Comment by keyur32** [comment]
As of right now, this capability doesn't exist (to return a 'variant' type), but is on our backlog. 

- For now, I'd recommend we return a Rejected Promise in your case above, and that will cause Excel to show #VALUE!:  https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Global_Objects/Promise/reject

**Comment by keyur32** [comment]
@mscharlock who will get our documentation updated to call out how to pass back errors.

**Comment by Zlatkovsky** [comment]
As a quick answer:  to return a rejected promise, just have your `.catch` block call a `reject` (and have your promise constructor take in both a `resolve` and a `reject`).  I.e.,:

    function BASIC(Ticker) {
        /// ...
        return new OfficeExtension.Promise(function (resolve, reject) {
            axios.get(url)
                .then(function() {
                    // ...
                })
                .then(function (json) {
                    // ...
                    resolve(result);
                })
                .catch(function (e) {
                    reject(e);
                });
            });
    }

**Comment by mscharlock** [comment]
@trionfo1993 I think the code provided by @Zlatkovsky should solve your issue. I'm going to close this issue, but can reopen if you have additional questions. :)
