### ISSUE TITLE
Do multiple user profiles have different storage instances in Excel on Windows

### ISSUE THREAD

**Issue by sshukurov** [OfficeDev/Excel-Custom-Functions#210]
`localStorage` in browsers is implemented so that it is unique for each browser user profile. Can I expect the same from `storage` in Excel on Windows? If I have multiple user profiles on my PC, does each user have their own storage instance in Excel on Windows?

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: d8364ff6-e963-8589-56f0-d4c46a95284c
* Version Independent ID: 14ac23fa-059a-b33f-4748-0d151becb18e
* Content: [Save and share state in custom functions - Office Add-ins](https://docs.microsoft.com/en-us/office/dev/add-ins/excel/custom-functions-save-state#feedback)
* Content Source: [docs/excel/custom-functions-save-state.md](https://github.com/OfficeDev/office-js-docs-pr/blob/master/docs/excel/custom-functions-save-state.md)
* Product: **excel**
* Technology: **add-ins**
* GitHub Login: @o365devx
* Microsoft Alias: **o365devx**

**Comment by keyur32** [comment]
Hi @wh1t3cAt1k ,  the storage api uses the Office cache: https://docs.microsoft.com/en-us/office/dev/add-ins/testing/clear-cache,  as demonstrated here: %LOCALAPPDATA%\Microsoft\Office\16.0\Wef\

This cache is per user, per device.

**Comment by wh1t3cAt1k** [comment]
Hi @keyur32 ! Thank you for the clarification!

Are there any platform differences in this? For example, what happens on Mac? Does it get stored under `/Users/USERNAME/Library/Application Support/` ?

What happens In Office on the Web?

I would also suggest to add this information to the documentation.

**Comment by wh1t3cAt1k** [comment]
To clarify, our scenario is that we need to "locally remember password":

**- without the user trusting our servers with their credentials (all is local)** (key value proposition),
- in a cross-platform manner (but we're okay if they need to do it separately for every platform, or if some platforms wouldn't be supported for this functionlaity)
- in a per-user scope so that the user can apply OS- or browser-provided security measures to ensure no one but them reads from that location.

We were wondering if OfficeRuntime.storage is an appropriate solution for this, and if not, what would be a viable OfficeJS alternative.

**Comment by wh1t3cAt1k** [comment]
Hey @keyur32 , just pinging you in case you were busy with something else.

**Comment by wh1t3cAt1k** [comment]
Hey guys, no pressure, but this went without answer for quite a while.

The ability to securely store passwords client-side is a crucial decision-making point for our product. Can anyone give me a hand with this?

**Comment by keyur32** [comment]
Hey @wh1t3cAt1k,  the mechanisms we have like the storage api stores on as plain text on the local machine in the Office Add-ins cache.  Based on that would recommend you take the appropriate pre-cautions (i.e. store a short lived access token vs the password) in that cache. 

thanks

**Comment by wh1t3cAt1k** [comment]
@keyur32 thank you! Could you please also clarify about the following:

> Are there any platform differences in this? For example, what happens on Mac? Does it get stored under /Users/USERNAME/Library/Application Support/ , or somewhere else?
> 
> Where is the OfficeRuntime.storage located in Office on the Web?

**Comment by keyur32** [comment]
Hi there, sorry for delay. This is documented here on the different cache locations that are used: https://docs.microsoft.com/en-us/office/dev/add-ins/testing/clear-cache   (OfficeRuntime.storage saves to a storage folder under that cache). Thanks!
