### ISSUE TITLE
Cors issue with shared runtime

### ISSUE THREAD

**Issue by vikasm1720** [OfficeDev/Excel-Custom-Functions#212]
The documentation says custom functions will have full cors support with shared runtime, but I still see an issue for functions.json file. functions.json is referenced under metadata tag in the manifest.xml. Can you please update the documentation for configuring functions.json metadata.

Access to XMLHttpRequest at 'https://{domain}.com/office_apps/functions.json' from origin 'https://inc-excel.officeapps.live.com' has been blocked by CORS policy: No 'Access-Control-Allow-Origin' header is present on the requested resource.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: dc89eff2-1c69-c80f-2cfb-43746309f2b7
* Version Independent ID: af86e11c-93ec-c0d9-bccd-cdd993fce37c
* Content: [Run your add-in code in a shared JavaScript runtime - Office Add-ins](https://docs.microsoft.com/en-us/office/dev/add-ins/excel/custom-functions-shared-overview)
* Content Source: [docs/excel/custom-functions-shared-overview.md](https://github.com/OfficeDev/office-js-docs-pr/blob/master/docs/excel/custom-functions-shared-overview.md)
* Product: **excel**
* Technology: **add-ins**
* GitHub Login: @o365devx
* Microsoft Alias: **o365devx**

**Comment by mscharlock** [comment]
@RuoyingLiang do you mind responding to this? Thanks!

**Comment by shaofengzhu** [comment]
The CORS support means that the addin could access the resources from another domain if the server allows the resources to be accessed from another domain. Without SharedRuntime, even if the server allows the resources to be accessed from another domain, the addin cannot access it. With SharedRuntime, the addin could access the resource as long as the server allows the resources to be accessed from another domain. For the custom-functions.json file, it's accessed by the browser JavaScript code from the Excel online domain. If the server does not allot the file to be accessed from another domain, the Excel online domain cannot access it and the custom function feature will not work. Please configure the server to allow custom-functions.json to be accessed from other domains.

**Comment by vikasm1720** [comment]
@shaofengzhu Thank you for the explanation. I am clear on concept of shared runtime. I have configured the server to allow functions.json to be accessed from other domains and it is working. I am closing this issue.

**Comment by sukanta88** [comment]
> @shaofengzhu Thank you for the explanation. I am clear on concept of shared runtime. I have configured the server to allow functions.json to be accessed from other domains and it is working. I am closing this issue.

can you please tell me how you did it?

**Comment by vikasm1720** [comment]
I have installed the IIS Cors module on the server and configured the web.config file to allow other domains. Follow the steps mentioned here.
[](https://learn.microsoft.com/en-us/iis/extensions/cors-module/cors-module-configuration-reference#cors-configuration)
