### ISSUE TITLE
Issue with "require package"

### ISSUE THREAD

**Issue by YaweiWang95** [OfficeDev/Excel-Custom-Functions#219]
*** NOTE: If you have an issue running your custom function, please log an issue in the official office-js repo here: [https://github.com/OfficeDev/office-js/issues](https://github.com/OfficeDev/office-js/issues) ***

In my custom function, I tried to include some package such as "ffi", "ref" using require sentence. However, the add-in will show error when starting debug. And here is the error message from "OfficesAddins.log".

Verbose	Runtime	[Console] [Log] Unexpected CustomFunctions [Execution] [End] [Failure] [ExceptionThrown] Function=PRIME_SIEVE TypeError: Object doesn't support property or method 'captureStackTrace' {}

**Comment by weshi** [comment]
What do you want to achieve with ffi? It seems this package is used to load files from local file system. But custom functions cannot only include files from the http server. I'm closing this. If this is not the case, please reactive this.

**Comment by YaweiWang95** [comment]
I want to include some functions developed in c++. Do you mean that the
custom function can only include files from http server? Then the right way
is first put the local functions into the server, then include the function
through web server?

**Comment by weshi** [comment]
No, you cannot do it with the custom functions. It can only include JavaScript functions, not C++ functions.

**Comment by YaweiWang95** [comment]
Yes, I understand that the custom function can not include C++ function
directly. How about using Native addon or through other package such as
emscripten. If these ways are’t available, is there any alternative way?
The ultimate goal is to use the built c++ library in excel through web
service.

**Comment by weshi** [comment]
Custom Functions is to run cross-platform (Mac/Online/Windows). C++ functions will not run on Excel on the Web. If your goal is to run it on Windows, you either develop traditional COM Add-ins or Excel XLLs. If you already have your XLLs, but still wants to use Custom Functions in Web add-in to call them on Windows, then you can refer to [Extend custom functions with XLL user-defined functions](https://docs.microsoft.com/en-us/office/dev/add-ins/excel/make-custom-functions-compatible-with-xll-udf).

**Comment by YaweiWang95** [comment]
Thanks for your suggestions. It’s very helpful.
