### ISSUE TITLE
Custom functions with latest release build

### ISSUE THREAD

**Issue by georgechr** [OfficeDev/Excel-Custom-Functions#22]
Will the sample (and to that extend, custom functions) work with the latest builds of office-js, 1.1.8 or 1.1.9? 
As far as I can see neither `Excel.CustomFunctions` or `Office.Preview.StartCustomFunctions` exist anymore. 

Can you provide us with a sample working against the latest versions of office-js?

EDIT: Just noticed that a '1.1.9-custom-functions-preview.5' tag exists. Still, what are the plans for merging this into the release tags? And where can we find detailed release notes for each release?

**Comment by keyur32** [comment]
Hi George,

Custom Functions is still in preview so you can get that access by referencing, as shown in this repo:
`https://unpkg.com/@microsoft/office-js@custom-functions-preview/dist/office.js`

While the feature is in preview, we are maintaining release notes here: https://docs.microsoft.com/en-us/office/dev/add-ins/excel/custom-functions-overview#changelog

Was your question more around when we'll have custom functions functionality available as part of the public 'office-js'?  If so, our plans are we'll have a separate javascript file published to our CDN, 'office.customfunctions.js' which will let you use both customfunctions.js and the rest of the office.js references.  We'll update the changelog and this repo when this is avaiable.

Can you describe your scenario?

**Comment by georgechr** [comment]
@keyur32 Thanks for your response.

My question was mostly answered in a [stackoverflow question](https://stackoverflow.com/questions/51383756/add-custom-functions-to-task-pane-add-in/51681432) by yourself!

We're working on a task pane add-in at the moment and we would like to call and set custom functions on the worksheet based on certain actions/parameters coming from the task pane. 

Furthermore, and more important, the custom functions we wish to define will share almost all of their logic with functionality that exists in the task pane. Thus, we would like to be able to:
* Host both custom functions and task pane within the same add-in (I believe this would be possible)
* Set and invoke custom functions from the task pane app (will also be possible from what I can understand)
* Share functionality between the task pane and custom functions (the workaround for this is to compile all custom logic into a shared 'customfunctions.js' file which will double up as the custom functions file + a sort of library to be used by the task pane)

**Comment by keyur32** [comment]
thanks for the additional details above.Yes all of those should work, along with your mechanism to share code between your customfunction and taskpane. The caveat there is to make sure it works with the new runtime changes that were pushed out to Windows Insiders builds: https://aka.ms/customfunctions for more info.

**Comment by keyur32** [comment]
Closing for now, feel free to reactivate if needed
