### ISSUE TITLE
OfficeRuntime.storage.setItems fails to set items in storage, return Unknown Error

### ISSUE THREAD

**Issue by mastershif** [OfficeDev/Excel-Custom-Functions#221]
I created an Excel add-in where the user need to log in first to use the add-in functionality.
The login happens in the taskpane.
When the user successfully logged in, I am calling OfficeRuntime.storage.setItems in order to save the user's details (email, token, etc.) in the storage. In Excel web it works properly but in Excel desktop this call fails, and the error returning from the promise is "Unknown: an unknown error has occurred".

The add-in is installed via the store. The Excel version is 2019.
This bug does not happen to all users, only some of them.

Operating System: Microsoft
Node version: v10.15.0
Office version: 2019
This is the function I'm running:

`const saveUserInfoInStorage = (token: string) => { return OfficeRuntime.storage .setItems({ [CONSTANTS.TOKEN_STORAGE_KEY]: token, [CONSTANTS.USER_ORGANIZATION]: getDomainFromEmail(username), [CONSTANTS.USER_EMAIL]: username, [CONSTANTS.FLOW_ID]: actualFlowId }); };`

**Comment by xiaochunms** [comment]
Is it possible to share manifest file which is helpful for debugging? As there is a log in step, it would be much helpful to have a test account that can login for debug.

**Comment by mastershif** [comment]
@xiaochunms thank you! 
the add-in is in the store, it is called AmenityAnalytics.
test account: amenity.addin.test@gmail.com Tufcyz5pithe

**Comment by xiaochunms** [comment]
@mastershif thanks for your information. I installed the add-in and logged in successfully with the test account. However I did not hit the Unknown error. My office excel version details is:

![image](https://user-images.githubusercontent.com/1261601/88755359-8fbac080-d193-11ea-94ae-71a5bf52aa22.png)

Could you share your excel version details by Excel->Account->About Excel?

**Comment by mastershif** [comment]
@xiaochunms this is the excel version:

![image](https://user-images.githubusercontent.com/14184076/88782344-24beb900-d196-11ea-93e2-de5715c10d62.png)

**Comment by lindalu-MSFT** [comment]
Hi, sorry for the delayed response! We're a bit short on resources this week due to vacations. I assigned this to the custome functions team to investigate. Thanks, linda

**Comment by ElizabethSamuel-MSFT** [comment]
@xiaochunms Any update on this? Thx.

**Comment by millerds** [comment]
@mastershif  are you still having trouble?
@xiaochunms are you still helping this person?

This doesn't look like a problem with the code in this repo, but rather challenges in coding specific behavior. Closing now. If you feel it needs more attention please reopen.
