### ISSUE TITLE
Excel online: Function replaced with #REF! when pasted to another workbook

### ISSUE THREAD

**Issue by fds-ssg** [OfficeDev/Excel-Custom-Functions#224]
# Expected behavior

The name of the function should appear the same when pasted as it did in the copied cell.

# Current behavior

In Excel online, if we copy a cell with a formula containting our custom function, `FDS()`, to a cell on a different workbook, every FDS() function call is replaced by `#REF!`.  For example:

Formula copied from Book 1: `=3*FDS("msft","price")+7`  
When pasted into Book 2, appears as: `=3*#REF!("msft","price")+7`

In both workbooks, the add-in containing the custom function is loaded and cells with the function have already been successfully evaluated.

Note that the following operations do successfully duplicate the formula:
* Copying the formula between cells within a workbook, including on different sheets
* Copying the text of the formula and pasting that into a different workbook

I have tried the same steps with a custom function created via Script Lab, and copying that between workbooks succeeds.

## Steps to Reproduce

Please provide detailed steps for reproducing the issue.

1. Install [our add-in](https://appsource.microsoft.com/en-us/product/office/WA200001456?src=retail&tab=Overview) 
2. The add-in requires authentication to return actual results, but should successfully return a default string (`#Calc`) even if not authenticated
3. Ensure two workbooks are open with the add-in available in each
4. Enter a formula with an FDS function, e.g. `=FDS("msft","price")`; the result should be `#Calc`
5. Copy the cell containing the formula and paste it into the second workbook
6. The result is that every instance of FDS is replaced by `#REF!`

## Context

This occurred using Excel online in Chrome.

Ways in which our add-in's custom functions differ from the Script Lab sample:
1. We don't have any name spacing
2. We use the [EquivalentAddins](https://docs.microsoft.com/en-us/office/dev/add-ins/reference/manifest/equivalentaddins) feature

**Comment by RuoyingLiang** [comment]
Thanks for reporting. I can repro the issue with your add-in. Will work with Excel Online copy&paste team to investigate.

**Comment by millerds** [comment]
If it's resolved (resolution:external) and in our backlog we don't need this issue anymore.
