### ISSUE TITLE
Flexbox Layout

### ISSUE THREAD

**Issue by nathanhammond** [OfficeDev/Excel-Custom-Functions#252]
The `flexbox` layout included in this sample code can easily cause issues in IE11, which is a semi-required target for deploying Excel Add-ins. An overflow layout issue caused by flexbox quirks in IE11 (correctly) resulted in a rejection during review.

I recommend switching to a different CSS layout pattern for the template layout.

**Comment by millerds** [comment]
We're no longer enhancing templates for IE11.
