### ISSUE TITLE
Dynamics array with Custom Functions

### ISSUE THREAD

**Issue by CristovaoTorres** [OfficeDev/Excel-Custom-Functions#253]
Hi.

I would like use Dynamics array Excel in my Custom Function.
is it possible?
How Can I use in my Custom Functions filters?

![image](https://user-images.githubusercontent.com/46796748/107780598-a5ee2f80-6d25-11eb-828a-22af836f629e.png)

read more
https://insider.office.com/en-us/blog/dynamic-arrays-and-new-functions-in-excel

**Comment by davidchesnut** [comment]
Hi @CristovaoTorres,  if you're just looking to return a dynamic array from your custom function, check out the article: [Return multiple results from your custom function](https://docs.microsoft.com/office/dev/add-ins/excel/custom-functions-dynamic-arrays)

Hope this helps!
David

**Comment by CristovaoTorres** [comment]
Tks.

I would like to receive an array as a parameter in may custom function.
exemple:
![image](https://user-images.githubusercontent.com/46796748/107835445-4b31f380-6d78-11eb-9653-25cc41a1e08a.png)

**Comment by CristovaoTorres** [comment]
.

**Comment by davidchesnut** [comment]
Hi @CristovaoTorres, to pass the dynamic array, the user needs to append `#` to the end of the dynamic array formula. For example, if B2 has a dynamic array that displays a range of 10 rows of data, you would pass it to your own function in another cell by entering `=mycustomfunction.secondHighest(B2#)`. In JS you receive the [value as a range](https://docs.microsoft.com/office/dev/add-ins/excel/custom-functions-parameter-options?tabs=javascript#range-parameters).

If you still need help can you ask this question on stackoverflow with the tag `office-js`? 

Hope this helps,
Thanks!
