### ISSUE TITLE
Localhost SSL requests 

### ISSUE THREAD

**Issue by awasser-omnispear** [OfficeDev/Excel-Custom-Functions#254]
I'm building a set of Custom Functions which connects to a server using WebSockets; just the standard WebSockets baked into the JS engine, not Socket.IO or any external library.
Connecting to the socket on the test and production server works great, but attempting to connect to localhost does not.  Taskpane connections work fine.
The error it gives is: `The certificate authority is invalid or incorrect`.  

Fetch requests also do not function.  Not immediately erroring out, but responding with a status = '0'.  The server never sees the request.
I am using SSL for both websockets (wss) and fetch (https) requests.  

Taskpane connections work fine, but custom function connections do not.
Websocket and fetch requests targetting external servers also work fine.

**Comment by nkkinariwala** [comment]
@awasser-omnispear - Thank you for posting a question. Can you please provide these additional details?

Your Environment
Platform: ______
Host: Excel
Office version number:______
Operating System: ______
Browser (if using Office on the web): ______

**Comment by awasser-omnispear** [comment]
Server platform:  WSL - Ubuntu 20
Host: Excel Desktop - (not using Shared Runtime)
Office version: 2101 (Build 13628.20380) - Current Channel
Operating System: Windows 10 Pro version 2004 (Build 19041.804)

I'm using WSL2 to run the webserver locally.  The taskpane runtime is able to connect to it, but the custom functions runtime cant seem to connect.

**Comment by grangeryy** [comment]
@awasser-omnispear did you use the [shared runtime?](https://docs.microsoft.com/en-us/office/dev/add-ins/tutorials/share-data-and-events-between-custom-functions-and-the-task-pane-tutorial)

**Comment by awasser-omnispear** [comment]
External requirements prevent me from using the shared runtime while it is still using Internet Explorer's engine.
As such, I cannot use shared runtime at the moment.

**Comment by grangeryy** [comment]
Custom function currently only handles external request in this [way](https://docs.microsoft.com/en-us/office/dev/add-ins/excel/custom-functions-web-reqs). 

From your description at the very beginning, does your custom function work together with taskpane or they are totally separate add-ins? If they need to work together, then you'll need to use shared runtime to make it happen.

**Comment by awasser-omnispear** [comment]
I've discovered the cause.  It is related to how I generated the localhost SSL cert and keys, not the custom functions runtime.
