### ISSUE TITLE
Custom Functions not registered with "Volume License"

### ISSUE THREAD

**Issue by JeremyJonas** [OfficeDev/Excel-Custom-Functions#265]
# Expected behavior
Should be able to develop **Excel Add-in with custom function** using **Volume License** on Mac.

# Current behavior
**Custom functions** are not registered in Excel during development do to *licensing* error, not supporting **Office License**, in my case **Volume License 2019**.

> This add-in is only supported with your Microsoft 365 subscription and is not supported with your Office license. Please contact your administrator for more information.

I have contacted my administrator and verified *Volume License 2019* for corporation should not be restricted.

## Steps to Reproduce

Please provide detailed steps for reproducing the issue.

1. Have *Microsoft Volume License 2019*
2. Following [excel-custom-functions-quickstart](https://docs.microsoft.com/en-us/office/dev/add-ins/quickstarts/excel-custom-functions-quickstart?tabs=excel-windows) tutorial
3. After `npm run start`, the `This add-in is only...` error should be in status bar.
4. Attempt to use default custom function: `=CONTOSO.ADD(10,200)` will get `#NAME?` error

## Context

* Operating System: `macOS Catalina 10.15.7 (19H524)`
* Node version: `v12.19.0`
* Office version: `2019`
* Tool version: `Excel 16.47 (21031401)`

![image](https://user-images.githubusercontent.com/464119/113476161-e35c7700-94a3-11eb-88e7-d9ae74b5c45a.png)

## Failure Logs

Screenshot of the error message in status bar:
![image](https://user-images.githubusercontent.com/464119/113475313-14867880-949f-11eb-981f-75962d795e50.png)

Screenshot of runtime logs showing attempt to *register* custom function:
![image](https://user-images.githubusercontent.com/464119/113476102-70eb9700-94a3-11eb-9a01-9ca463b38b6f.png)

Full runtime log:
[runtime.log](https://github.com/OfficeDev/Excel-Custom-Functions/files/6252369/runtime.log)

Similar to #193

**Comment by grangeryy** [comment]
@JeremyJonas, is the Volume License also under O365 or one-time purchase version? Currently, excel custom functions are not supported in Office 2019 (one-time purchase):
![image](https://user-images.githubusercontent.com/50093161/113830357-2165dd80-97b9-11eb-8f7f-b91c056b4adf.png)

**Comment by JeremyJonas** [comment]
Hi @grangeryy, it is one-time purchase volume license. Is this requirement in the documentation? Any plans to support this? Thank you!

**Comment by grangeryy** [comment]
Hey @JeremyJonas, the requirement is in the documentation "Note" section. Unfortunately we don't have a plan to support this so far. Custom functions will work together with dynamic array feature, which is also not supported in Office 2019. So in your case, you may need to upgrade to O365 subscription or wait for 2021(or called vNext, targeting June this year.)
