### ISSUE TITLE
TypeError: Network request failed - windows desktop excel

### ISSUE THREAD

**Issue by avinashmadireddy** [OfficeDev/Excel-Custom-Functions#275]
*** NOTE: If you have an issue running your custom function, please log an issue in the official office-js repo here: [https://github.com/OfficeDev/office-js/issues](https://github.com/OfficeDev/office-js/issues) ***

All of our custom functions are working fine in online and mac desktop versions. But failing in only windows desktop version.

"Network request failed" issue happening on windows desktop excel.

We are firing POST request to our gateway.

Implemented shared runtime based on "https://docs.microsoft.com/en-us/office/dev/add-ins/develop/configure-your-add-in-to-use-a-shared-runtime", which resulted all the custom functions failed in all versions (desktop and online)

Any help?

Thanks!!

**Comment by slabereemsft** [comment]
Hi Avinashmadireddy,

Have you tried using a fiddler trace to get more information about what the network call is that is failing? That might help us diagnose the issue more quickly.

**Comment by avinashmadireddy** [comment]
Thanks. I've not tried fiddler. Will let you know what fiddler says.

**Comment by csreddyennam** [comment]
Log to logger, follow below link
https://docs.microsoft.com/en-us/office/dev/add-ins/testing/runtime-logging#runtime-logging-on-windows

**Comment by avinashmadireddy** [comment]
@slabereemsft No trace in fiddler when executing the custom function on windows desktop version. Also tried on Mac excel version (working), where fiddler is tracing the rest call that's getting invoked from custom function.

I've gone the Microsoft documents and they suggested to use the shared javascript runtime as we are implementing the UI less custom functions. [https://docs.microsoft.com/en-us/office/dev/add-ins/develop/configure-your-add-in-to-use-a-shared-runtime](url).

After implementing the shared javascript runtime, the application is failing in all versions (desktop / online - Windows/Mac). Before this changes, it is working in all except windows desktop version.

**Comment by avinashmadireddy** [comment]
After implementing shared javascript runtime, the UI less custom functions are getting loaded to the excel but when tried to execute them no action. Following is the error

Uncaught TypeError: i.getInitializationReason is not a function
    at office.js:46
    at d (office.js:46)
    at f.waitForFunction (office.js:46)
    at j (office.js:46)
    at OSF.InitializationHelper.loadAppSpecificScriptAndCreateOM (excel-web-16.00-core.js:18)
    at office.js:46
    at f.invokeCallbackIfScriptsReady (office.js:46)
    at f.waitForScripts (office.js:46)
    at office.js:46
    at Object.d [as callback] (excel-web-16.00-core.js:18)


Any help?

**Comment by grangeryy** [comment]
@avinashmadireddy guess the resources are hosted in the localhost? Could you help to share your project to us so we can be more efficient to debug the issue?

**Comment by avinashmadireddy** [comment]
@grangeryy Yes, the resources are hosted in localhost. I'll share the two projects, with and w/o shared runtime.

**Comment by avinashmadireddy** [comment]
@grangeryy Invited you to the "UI less custom functions with shared runtime" project. Due to security reasons i've deleted content in task pane and dialogues (TODO). For now I've added only one basic custom function FS.add(). This custom function is getting registered with the excel but not getting invoked during execution. For info, there are other custom functions which will contact our gateway to fetch the data (POST request with headers).

Let me know if you need more on this.

**Comment by xiaochunms** [comment]
@avinashmadireddy could you please also loop me in your project? I can take a look from developer's perspective.

**Comment by grangeryy** [comment]
@avinashmadireddy please also include 2xiaochunms as he is our engineer who will be investigating this. THX! @

**Comment by avinashmadireddy** [comment]
@grangeryy @xiaochunms Looks like you have not accepted my invite for the project. 

I've updated the project "ui-less-custom-func-wo_sr" and logged an issue, where you can get clear idea whats happening after running the project in windows desktop & online version.

**Comment by xiaochunms** [comment]
@avinashmadireddy I tried to look for notifications in system on project invitations but I did not find it. :( I am thinking to ask you the project detail information on how to access. It is great that you shared the link. :) Thanks for the invitation and I can access projects now. I will take a look at my side and will be back to you soon.

**Comment by avinashmadireddy** [comment]
@xiaochunms Thanks. 

[https://github.com/avinashmadireddy/ui-less-custom-func-wo_sr](https://github.com/avinashmadireddy/ui-less-custom-func-wo_sr) is without shared runtime

[https://github.com/avinashmadireddy/ui-less-custom-func-wsr](https://github.com/avinashmadireddy/ui-less-custom-func-wsr) is with shared runtime

**Comment by xiaochunms** [comment]
@avinashmadireddy Thanks for the information. I tried both and may want to share following information:
1. I tried the without shared runtime project at my side, it works fine. I am thinking the issue you hit may be related with the value of "UseDirectDebugger" registry key. You can have a check and add it in the registry.

![image](https://user-images.githubusercontent.com/1261601/119606527-51c71100-be25-11eb-83e9-1216ed363df0.png)

2. Regarding to the shared runtime project, I noticed there are several issues with the manifest file. Following patch contains changes I made to make custom functions work. (Please stripe .txt suffix as .patch is not supported to be attached.)
[0001-Fix-manifest-issues.patch.txt](https://github.com/OfficeDev/Excel-Custom-Functions/files/6544053/0001-Fix-manifest-issues.patch.txt)

Any further request please kindly to let me know.

**Comment by avinashmadireddy** [comment]
@xiaochunms Thanks. I'll try both suggested solutions and let you know.

Reg. project with out shared runtime, how it will work if we go live. 
Currently we deployed our project (w/o shared runtime) through central deployment and it fails in only windows desktop version. How to debug this case at user end. The excel build version they are using supports custom function.

**Comment by avinashmadireddy** [comment]
@xiaochunms @grangeryy 

I've tried the solution provided for shared runtime and it worked. 

Is the "taskpane html & js" are required to be part of the project? Actually I tried to use a different html file which will used to be display in the taskpane area and included the "functions.js"in this file.

Thanks for solving the issue.

One more observation, in shared runtime environment the dialog box is not opening in a new windows in online version. Is this expected?

    Office.context.ui.displayDialogAsync(window.location.origin +  '/loginhtml', {height: 70, width: 50, displayInIframe: false}

After setting displayInIframe to true it started working

**Comment by xiaochunms** [comment]
@avinashmadireddy good to know your project works finally. In shared runtime case it still can work if using a different html file other than taskpane html, you may can treat taskpane html as an sample and make corresponding changes based on it. However functions.js file should be always included in the html file. 

Regarding to displayDialogAsync API, good to know it works to set displayInIframe to true. Checking the description of "displayInIframe", "If false (default), the dialog will be displayed as a new browser window (pop-up)." Is it possible the pop-up window is blocked?

Frankly speaking it is hard to debug custom functions without shared runtime at user end. I may suggest to switch to shared runtime which will not lose any functionality but gain debuggabilities at user end.

**Comment by avinashmadireddy** [comment]
@xiaochunms After making shared runtime working, displayDialogAsync API is failing (online version) if set "displlayInframe" to false.

As the dialog is intended to perform Microsoft SSO login, it's suggested to open in new windows.

pop-up is not blocked in my case. Any further suggestions? 

If you need, I'll add the piece of code our test project.

**Comment by xiaochunms** [comment]
Yes, please add codes in test project. I can take a further look then.

**Comment by avinashmadireddy** [comment]
@xiaochunms @grangeryy 

SSO Login is working as expected except in safari browser. I'll try to resolve this. If any help required I'll create a new issue.

Thanks for the suggestions in resolving the custom functions issue.
