### ISSUE TITLE
Add-in broke suddenly

### ISSUE THREAD

**Issue by gitty-git-git** [OfficeDev/Excel-Custom-Functions#285]
Please answer the following questions before submitting an issue. 
**YOU MAY DELETE THE PREREQUISITES SECTION.**
- [ x ] I am running the latest version of Node and the tools
- [ x ] I checked the documentation and found no answer
- [ x ] I checked to make sure that this issue has not already been filed

# Expected behavior

Please describe the behavior you were expecting

# Current behavior
I have an Add-in that is on the marketplace that people use. I have not made any changes to it for a while. Suddenly last week it broke on both the web and desktop versions. On the web, users have to continually click "Trust this add-in" button everytime they want to use the Add-in. On desktop, there is a different behaviour: the user just sees `#BUSY!` when they put in my custom formula and `#BUSY!` doesn't go away.

Please provide information about the failure. What is the current behavior? If it is not a bug, please add it to [UserVoice](https://officespdev.uservoice.com/forums/224641-feature-requests-and-feedback/category/164751-office-developer-tools), so that it gets added to our feature roadmap.

## Steps to Reproduce

Please provide detailed steps for reproducing the issue.

1. step 1
2. step 2
3. you get it...

## Context

Please provide any relevant information about your setup. This is important in case the issue is not reproducible except for under certain conditions.

* Operating System: Desktop and web version (using Chrome and probably other browsers as well)
* Node version:
* Office version:
* Tool version:

## Failure Logs

Please include any relevant log snippets, screenshots or code samples here.

**Comment by gitty-git-git** [comment]
My suspicion is that Excel had an update that broke things in the past week or two. Does Excel need to rollback that update(s)?

**Comment by gitty-git-git** [comment]
I should add that on the desktop version the issue is fixed if the users uninstalls the add-in, installs it again and restarts excel. So, the problem is not with the add-in itself.

**Comment by nkkinariwala** [comment]
@gitty-git-git  - can you please provide more details? like are you the user of an Add-in or the developer of an Add-in? If the Add-is on the marketplace, can you please let us know which Add-in are you talking about? Also the version of Excel desktop.
