### ISSUE TITLE
 Custom Functions run well on Desktop, but always be #N/A on Web

### ISSUE THREAD

**Issue by neittien0110** [OfficeDev/Excel-Custom-Functions#286]
**Description:**
 - A very simple functions of a add-in project could run well on the Excel Desktop version. 
 - The custom function could run well on the Script Lab on Excel for Web 
 - The add-in deploy successfully on Excel for Web,
 - but all its custom functions always return #N/A on Excel for Web
![image](https://user-images.githubusercontent.com/8079397/133477462-2a5c771f-6ab0-4bad-bdbb-6148348373ee.png)

**Elaborate more:**
**Please see [the video](https://youtu.be/_8cYgTKqUJQ)** and the test environment diagram
![image](https://user-images.githubusercontent.com/8079397/133477686-9d27ba83-83fa-4f4f-9911-eca9ecdbb2a1.png)

 - I have 2 add-in projects include a same custom function. One project is okay, another is fail.
 - In the video, from 0:00 to 01:00, I implemented the add-in on Excel for Desktop using the manifest point to a public server https://mycel.app:50000/. (I closed the local dev-server immediately after running the add-in to make sure that I have used the public server) It's okay.
 - from 1:00 to 2:05, I pasted a custom function to Script Lab on Excel for Web to make sure that the custom functions were good.
- from 2:05 to 3:22, I uploaded the same manifest to Excel for Web. However, all custom functions were not working.
 
At the moment, the public server is running. You could upload the manifest below to test now.
[manifest.release.xml.txt](https://github.com/OfficeDev/Excel-Custom-Functions/files/7172144/manifest.release.xml.txt)

**Comment by xiaochunms** [comment]
@neittien0110 Sorry to hear the issue. I think the missing of functions.js is the root cause for #N/A error here. Could you please add `<script type="text/javascript" src="functions.js"></script>` into walkthrough.html to load functions.js explicitly when opening the taskpane?

**Comment by neittien0110** [comment]
> @neittien0110 Sorry to hear the issue. I think the missing of functions.js is the root cause for #N/A error here. Could you please add `<script type="text/javascript" src="functions.js"></script>` into walkthrough.html to load functions.js explicitly when opening the taskpane?

Dear @xiaochunms,
Thank you for helping me. You are right. The solution is including the script functions.js in the html of the taskpane.

This issue take 2 working days of mine. The reason why I don't think about this script is:
 1. Declared functions.js and functions.json in the manifest clearly.  No need to declare them in the taskpane page.
May be I think, Excel for Desktop has more rights to get them, but Excel on Web cannot call them automatically.
 2. In some examples created by yeoman, there is no taskpane.html or functions.html. Finally, as your advice, I found that it replace taskpane.html by functions.html and using webpack to include the script.
![image](https://user-images.githubusercontent.com/8079397/133611254-64340c26-9aca-4c6f-938a-3787c13de1d9.png)

Many thanks

**Comment by akrantz** [comment]
@darrelmiller Please check whether the update to webpack 5 caused the custom functions webpack config to change. It should generate the functions.json, functions.js, and functions.html. 

Note that "npm run build" needs to be run before the dev-server so it writes the output files into the dist folder. The manifest points to /dist/functions.* because it cannot be served directly from the dev server since the custom functions runtime is not a browser context.

**Comment by akrantz** [comment]
This was closed but it might be work reopening if there is an issue here loading custom functions on the web.

**Comment by millerds** [comment]
The problem I was facing with not getting toe functions.js file is local only (not checked in yet) and is with an update to webpack-dev-server and manifests in the desktop.  This sounds similar, but not the same.

That said, it's probably worth looking into since as far as I know we shouldn't depend on the taskpane being opened to run custom functions.

**Comment by millerds** [comment]
I tried it and I was able to use the custom function from the raw template without having to open the taskpane.

**Comment by neittien0110** [comment]
@akrantz  in this case, i'm using webpack4. I make sure that both functions.json, functions.js, and functions.html are generated ( I could open them by the direct URIs). Somehow they cannot be loaded.

**Comment by millerds** [comment]
If you generate a new Custom Functions project using 'yo office' then you'll get a project setup to work with webpack 5 and webpack-dev-server 4.  It has some default functions there and should work for the web just by adding a document config property to package.json pointing to a test document.  You can use this as an example to figure out what the difference is with your own function setup.
