### ISSUE TITLE
Refresh all custom functions  in a specific sheet 

### ISSUE THREAD

**Issue by tqdo** [OfficeDev/Excel-Custom-Functions#298]
I am just curious how do I refresh all custom functions of my addin in a specific sheet using JavaScript? Thanks

**Comment by millerds** [comment]
What do you mean by "refresh all the custom functions" . . . are you talking about re-running the function code or refreshing the function definitions or something else?

**Comment by tqdo** [comment]
Sorry for not being clear. What I mean is to rerunning all the custom function in a current active sheet when user clicks a button in the sidebar of my add-in

**Comment by millerds** [comment]
You mean like use this api: https://docs.microsoft.com/en-us/javascript/api/excel/excel.worksheet?view=excel-js-preview#calculate_markAllDirty_

**Comment by Wenjun-Gong** [comment]
　Hi @tqdo,

Does the API calculate(markAllDirty) suggested by millerds work for you? Let us know if you have any further question. Thanks.

Wenjun

**Comment by Wenjun-Gong** [comment]
Hi @tqdo, I found a similar question on Stackoverflow: https://stackoverflow.com/questions/70219881/excel-add-in-refresh-all-custom-functions-in-a-specific-sheet
Please check whether it answers your question. Thanks.

**Comment by tqdo** [comment]
thanks it does
