### ISSUE TITLE
Question: Is it possible to have Streaming Functions working with requiredAddresses?

### ISSUE THREAD

**Issue by bryancr89** [OfficeDev/Excel-Custom-Functions#303]
Hi there!

I have a streaming function that accepts a cell like `=MyStreamFunction(A1)`, but I'm unable to get the address of that parameter. The documentation saids that Stream Functions doesn't work with @requiredAddresses.

Do you know if it's possible to access it somehow or why it is not enabled?

**Comment by tqdo** [comment]
+1, I also need this feature

**Comment by grangeryy** [comment]
Hey @bryancr89 and @tqdo , this is a new feature ask and we have a backlog item in tracking: 5517742

**Comment by grangeryy** [comment]
@bryancr89 and @tqdo, internally this ask is still tracking in our backlog. To make it more visible to people who have the same ask, we recommend you posting the requirement in [Ideas Forum](https://techcommunity.microsoft.com/t5/microsoft-365-developer-platform/idb-p/Microsoft365DeveloperPlatform) (which is a new version of "UserVoice").
