### ISSUE TITLE
excel Mac ghost user defined functions with no add-in loaded.  "This add-in is no longer available"

### ISSUE THREAD

**Issue by dkauper** [OfficeDev/Excel-Custom-Functions#306]
1. previously side-loaded a yo generated custom functions add-in
2. now, with no add-in loaded, the four custom functions are still present in any excel file opened.
3. on attempt to use the custom functions, task pane opens with error message:  _This add-in is no longer available.  If this add-in's manifest was removed, please restore it to its previous location and try again_.
4. I simply want to remove reference to these custom add-ins and get on with attempts at creating other add-ins.
5. Non of the MS instructions for clearing the cache work.
6. I've restarted in safe mode.  Same result.

Anyone know where the reference to the custom functions is stored or how to get rid of it?

**Comment by millerds** [comment]
They are probably still in the cache.

https://docs.microsoft.com/en-us/office/dev/add-ins/testing/clear-cache#:~:text=From%20the%20ribbon%20of%20any%20Office%20host%20except,Excel%2C%20Word%2C%20and%20PowerPoint%20is%20different%20from%20Outlook.

**Comment by dkauper** [comment]
Thanks, millerds, but I've tried each of the locations mentioned in that article.
~/Library/Containers/com.Microsoft.OsfWebHost/Data/ is empty.
The others,
~/Library/Containers/com.microsoft.Excel/Data/Library/Caches, etc., don't exist on my Mac.
I'm running Monterey 12.2.1.
Perhaps Office 365 has moved the location of those folders but I can't seem to find them anywhere.

Anyone out there from Microsoft that can shed light on this?

**Comment by dkauper** [comment]
I found it!!!
~/Library/Containers/Microsoft Excel/Data/Library/Application Support/Microsoft/Office/16.0/Wef/CustomFunctions/v1.7

Searched for all "wef" folders.  Found 5 or 6 and went through each.  Thank you Darren Miller.
