### ISSUE TITLE
Suggestions on resolving #N/A error in custom functions

### ISSUE THREAD

**Issue by romglusker** [OfficeDev/Excel-Custom-Functions#307]
Hello,

We have an Excel Add-In, consisting of both custom functions & a taskpane, which is deployed via Centralized Deployment.

Several users have encountered #N/A errors in the custom functions, and it is often difficult to resolve the issue. Note that this is inconsistent: sometimes, it's only in Excel Web, sometimes it's only in Excel Desktop, sometimes it's for both. Other users do not encounter these issues at all, even for the same spreadsheets. All users are on Office 365.

We've found several troubleshooting steps which often help, but not always:

- Modifying cells which are referenced by the custom function
- Refreshing taskpane
- Closing and re-opening workbook
- Inspect Document > Removing Task Pane Add-ins 
- Clearing the Office cache
- Restarting computer
- Repairing Office

Are there any known issues regarding the registration of custom functions? 

[Documentation](https://docs.microsoft.com/en-us/office/dev/add-ins/excel/custom-functions-troubleshooting#check-for-excel-error-messages) says that "A #N/A error is also maybe a sign that that function while registered could not be run. This is typically due to a missing CustomFunctions.associate command". However, the code is not missing a CustomFunctions.associate command, as evidenced by the fact that the formulas usually work fine.

Sorry if this is too open-ended, I'm mainly looking for recommendations if people have experienced this before. Could not find much documentation on this. Let me know if more information is needed.

Thanks!

**Comment by jasonclg** [comment]
I'm having the same #N/A issue for custom function on Excel Web only.
Not sure if it's related to https://github.com/OfficeDev/Excel-Custom-Functions/issues/257

**Comment by rundongmsft** [comment]
Hi @romglusker and @jasonclg, thanks for your report. Does this issue only occured in Centralized Deployment Add-ins? How to reproduce this issue?

**Comment by romglusker** [comment]
@rundongmsft That's a good question, I've mostly been testing through Centralized Deployment recently, so I'm not quite sure. When developing the Add-In, I think I had encountered the same (or similar) issue a few times through sideloading in Web. 

In this use case, it seems to have been resolved after a Windows update, which allowed Excel Desktop to prioritize using Microsoft Edge instead of Internet Explorer behind-the-scenes. 

The issue is really that it's difficult to reproduce, seems to happen randomly, some of the time, to some users, but not others. So I was mainly hoping if others have encountered something similar, if they had any tips. Usually the issue is resolvable after exhausting our list of potential troubleshooting steps, but it can sometimes be frustrating.

I'm okay with closing this issue if there is no tangible follow-up, because it's not readily reproducible.

**Comment by peronald** [comment]
@rundongmsft is there a follow-up to this issue. If not, can we close it?

**Comment by rundongmsft** [comment]
Thanks @peronald, there are no follow-ups, please close this issue.

**Comment by slabereemsft** [comment]
Closing per rundong
