### ISSUE TITLE
Sideloading valid manifest in Excel Web generates invalid result

### ISSUE THREAD

**Issue by jasonclg** [OfficeDev/Excel-Custom-Functions#308]
My test manifest file => https://gist.github.com/jasonclg/fa4bc51cdfd0ce82efbcb711aed06d45
The manifest was marked valid when running against validator locally
`npx office-addin-manifest validate manifest.xml`

It can be sideloaded successfully in Excel Desktop.
However, when I sideloaded it in Excel Web, "Your add-in manifest is not valid" popped up.

Some observations of behavior based on different resid combinations of the buttons
- if both buttons use **Taskpane.Url**, it's valid
- if neither button uses **Taskpane.Url**, it's valid
- if only one button uses **Taskpane.Url**, it's invalid (current code in gist)
- DefaultValue of the Url doesn't impact the result. **Taskpane0.Url** can be used in the failure case above to pass the validation even if its value is the same as **Taskpane.Url**.

Please advise what might cause the error.

Thanks!

**Comment by RuizhiSunMS** [comment]
Hello @jasonclg 
We suppose that you might should submit issue to https://github.com/OfficeDev/office-js/issues because we found this had no relationship with Custom Function after some investigation.
Thanks for reporting anyway.

**Comment by millerds** [comment]
@RuizhiSunMS, I think this may have something to do with custom functions and sharedruntime.  I encountered a similar problem in win32 Excel when trying to use shared runtime specifically.  The test passed before switching to shared runtime, but then started failing when the manifest used the same resid for the Runtime reference and the custom function extension point's page source tag.  Oddly enough if I use different resids pointing to the same html file the test starts passing.
