### ISSUE TITLE
NPM build produces mismatching names

### ISSUE THREAD

**Issue by tqdo** [OfficeDev/Excel-Custom-Functions#311]
# Expected vs Current behavior
I am following this [guide](https://docs.microsoft.com/en-us/office/dev/add-ins/quickstarts/excel-custom-functions-quickstart?tabs=excel-windows) to build custom functions. My app has a task pane.
The problem is when I run `npm run build`, all of the files are compiled into the `dist` folder. In that folder, there is a compiled `taskpane.html`, however the files included in `taskpane.html` are not the compiled files in the `dist` folder. I would expect their names match.
![Screen Shot 2022-03-19 at 7 59 01 PM](https://user-images.githubusercontent.com/53948469/159142429-99425f71-7b2c-4316-a837-71f580b853ea.png)
![Screen Shot 2022-03-19 at 7 58 22 PM](https://user-images.githubusercontent.com/53948469/159142430-3ae88470-3f33-4b3a-bd94-b62a38c2b743.png)

## Steps to Reproduce

Follow the steps in the [guide](https://docs.microsoft.com/en-us/office/dev/add-ins/quickstarts/excel-custom-functions-quickstart?tabs=excel-windows) , after that run `npm run build` in the terminal.

## Context

Please provide any relevant information about your setup. This is important in case the issue is not reproducible except for under certain conditions.

* Operating System: Mac OS
* Node version: 14.18.2
* Office version: 365

**Comment by davidchesnut** [comment]
@millerds is this something you could help with? Thanks!

**Comment by millerds** [comment]
What are the file references before you run 'npm run build'?

**Comment by tqdo** [comment]
Sorry I did not state the reproducing steps clearly. Here it is:

1/ Follow the steps in this [guide](https://docs.microsoft.com/en-us/office/dev/add-ins/quickstarts/excel-custom-functions-quickstart?tabs=excel-windows) to create a new project
2/ Go to /src/taskpane
3/ Create a JS file named `test.js` with 1-line content `var test_number = 3`
4/ Open /src/taskpane/taskpane.html
5/ In the `head` section, add this line: `<script type="text/javascript" src="test.js"></script>`
6/ Right before the `</body>`, add this line: `<script>console.log(test_number);</script>`
7/ Go to / and run `npm run build` to see the mismatching name.

So to answer your question, the file reference in /src/taskpane/taskpane.html before running `npm run build` is `<script type="text/javascript" src="test.js"></script>`

![Screen Shot 2022-03-28 at 4 24 01 PM](https://user-images.githubusercontent.com/53948469/160480893-2eed4d13-e8ed-4aa1-b0ef-79fe8a03d6a1.png)

**Comment by millerds** [comment]
Sorry for the delayed response.

I have reproduced the problem, but only for the production mode of webpack.  If you run 'npm run build:dev' to generate the files, then the javascript files references in the html file match the hashed file names.  This looks like something specific to webpack and I'm not familiar enough with it to know why the difference (given both commands are using the same webpack.config.js file).

@akrantz do you know why webpack would do this?

**Comment by millerds** [comment]
Finally got back to this.  

There is a github issue talking about this webpack problem and it has a workaround: https://github.com/jantimon/html-webpack-plugin/issues/1638

Another workaround would be to add test.js to the webpack config entry for the taskpane ('taskpane: "./src/taskpane/taskpane.js",' becomes 'taskpane: ["./src/taskpane/taskpane.js", "./src/taskpane/test.js"],') so the code is bundled together into just the one taskpane.js file.  There are probably other webpack config changes that could work around this as well.
