### ISSUE TITLE
Custom Functions not working in Web

### ISSUE THREAD

**Issue by titanous** [OfficeDev/Excel-Custom-Functions#312]
I tried loading [CFSample2](https://github.com/OfficeDev/custom-functions/blob/master/addins/cfsample2/c5a33478-ba81-414d-ad52-804f5da8facf.xml) into a workbook in Excel Web and no custom functions are showing up (the rest of the ribbon/taskpane functionality works fine, and everything works on Desktop).

I'm also seeing this issue with my own addin, it works fine on desktop but on Web the functions metadata JSON is never loaded and the functions don't show up.

**Comment by titanous** [comment]
I think this issue has been mislabled, I was not asked for feedback.

**Comment by davidchesnut** [comment]
Hi @titanous,

Sorry about that. I thought I had posted a response to this, but now I don't see it. I'll look into this again and follow up with you.

**Comment by davidchesnut** [comment]
@titanous btw if you use the dev tools in the browser to check the console for any errors, or to see if there's any HTTP errors for functions.json, that would be helpful to know. I do remember I loaded CFSample2 and it was working for me. So likely we need to do a little troubleshooting to find out what's happening.

Thanks!
David

**Comment by titanous** [comment]
I don't see any console errors related to loading functions.json. Here's a
[zip with the console logs and the HAR](https://github.com/OfficeDev/Excel-Custom-Functions/files/8359479/cfsample2_logs.zip) (I started recording the HAR after the document loaded, and then sideloaded the addin).

**Comment by titanous** [comment]
I'm using Chrome 99.0.4844.86.

**Comment by davidchesnut** [comment]
Hi @titanous,

You should see the following requests for CFSample json, js, and html.
![image](https://user-images.githubusercontent.com/8559338/160477775-711d2433-62a2-46f9-a1f0-68ed6d97e317.png)

Looking in your logs I don't see requests for those URLs which is odd. Well except for the button images, but that alone won't work.

BTW: The name for CFSample is custom-functions.json (not functions.json as I indicated earlier.)
Also I'm using Chrome 99.0.4844.82 so seems like there shouldn't be any significant difference there.

How are you sideloading the manifest? I'm sideloading the one you linked to at the beginning of this issue by manually uploading the manifest.xml file.

**Comment by titanous** [comment]
I'm sideloading by selecting the "Office Add-ins" action and then clicking the "Upload My Add-in" link and uploading [this manifest](https://github.com/OfficeDev/custom-functions/blob/master/addins/cfsample2/c5a33478-ba81-414d-ad52-804f5da8facf.xml). I only see the logo image being loaded. I get exactly the same result with my own custom add-in with a similar custom function config that works fine in Excel desktop on macOS.

I'm testing in an incognito window without any extensions loaded. I also tested in Chrome 99.0.4844.84 on macOS with the exact same result (I've been doing my testing on ChromeOS so far). Is it possible that I'm accessing a different build of Excel Web than you're using? I'm just using office.com, not sure if there are different feature flags or versions available. Also, is there any way to enable debug logging so we can see details of how the manifest is being parsed/handled?

**Comment by davidchesnut** [comment]
Online uses the same build for everyone, so we shouldn't see any differences there. I don't know of a way enable runtime logging for the manifest. @grangeryy is this issue something you could help with?

@titanous I am curious if you can run [Script Lab](https://appsource.microsoft.com/en-US/product/office/wa104380862) It has custom function samples you can run. If it also can't load custom functions that might indicate something is happening at the browser level settings.

Cheers,
David

**Comment by titanous** [comment]
I've figured out what's causing the issue: I had third-party cookie blocking enabled. After allowlisting all of the domains that wanted to set cookies, custom functions are now working as expected. It'd be great if you could add an error with the exact domains that need third-party cookies, and then remove this unfortunate requirement.

**Comment by grangeryy** [comment]
Great to know the issue was resolved! @titanous thank you for sharing the findings and providing feedback and suggestion here. We'll create a item in backlog, and track to improve the experience for using custom functions with cookie blocking setting.
