### ISSUE TITLE
Error when webpack hot-reloads (clean `yo office` project)

### ISSUE THREAD

**Issue by jasperchan** [OfficeDev/Excel-Custom-Functions#319]
Environment
- macOS 11.6.1
- Excel 16.59
- Microsoft 365 Personal Subscription

Running `yo office` with selections:
```
? Choose a project type: Excel Custom Functions Add-in project
? Choose a script type: TypeScript
? What do you want to name your add-in? rit-excel-addin-clean
```

And then running
```
npm run dev-server
```
from project root, I get a series of webpack errors whenever I edit one of the files in `src` (for example adding a no-op space and then saving the file):
```
ERROR in /Users/jasper/Repository/rit-excel-addin-clean/src/taskpane/taskpane.ts
./src/taskpane/taskpane.ts 37:33-36
[tsl] ERROR in /Users/jasper/Repository/rit-excel-addin-clean/src/taskpane/taskpane.ts(37,34)
      TS2304: Cannot find name 'add'.

ERROR in /Users/jasper/Repository/rit-excel-addin-clean/src/taskpane/taskpane.ts
./src/taskpane/taskpane.ts 38:35-40
[tsl] ERROR in /Users/jasper/Repository/rit-excel-addin-clean/src/taskpane/taskpane.ts(38,36)
      TS2304: Cannot find name 'clock'.

ERROR in /Users/jasper/Repository/rit-excel-addin-clean/src/taskpane/taskpane.ts
./src/taskpane/taskpane.ts 39:39-48
[tsl] ERROR in /Users/jasper/Repository/rit-excel-addin-clean/src/taskpane/taskpane.ts(39,40)
      TS2304: Cannot find name 'increment'.

ERROR in /Users/jasper/Repository/rit-excel-addin-clean/src/taskpane/taskpane.ts
./src/taskpane/taskpane.ts 40:33-43
[tsl] ERROR in /Users/jasper/Repository/rit-excel-addin-clean/src/taskpane/taskpane.ts(40,34)
      TS2552: Cannot find name 'logMessage'. Did you mean 'onmessage'?

ERROR in /Users/jasper/Repository/rit-excel-addin-clean/src/commands/commands.ts
./src/commands/commands.ts 46:33-36
[tsl] ERROR in /Users/jasper/Repository/rit-excel-addin-clean/src/commands/commands.ts(46,34)
      TS2304: Cannot find name 'add'.

ERROR in /Users/jasper/Repository/rit-excel-addin-clean/src/commands/commands.ts
./src/commands/commands.ts 47:35-40
[tsl] ERROR in /Users/jasper/Repository/rit-excel-addin-clean/src/commands/commands.ts(47,36)
      TS2304: Cannot find name 'clock'.

ERROR in /Users/jasper/Repository/rit-excel-addin-clean/src/commands/commands.ts
./src/commands/commands.ts 48:39-48
[tsl] ERROR in /Users/jasper/Repository/rit-excel-addin-clean/src/commands/commands.ts(48,40)
      TS2304: Cannot find name 'increment'.

ERROR in /Users/jasper/Repository/rit-excel-addin-clean/src/commands/commands.ts
./src/commands/commands.ts 49:33-43
[tsl] ERROR in /Users/jasper/Repository/rit-excel-addin-clean/src/commands/commands.ts(49,34)
      TS2552: Cannot find name 'logMessage'. Did you mean 'onmessage'?

8 errors have detailed information that is not shown.
Use 'stats.errorDetails: true' resp. '--stats-error-details' to show it.

webpack 5.52.1 compiled with 8 errors in 652 ms
```

Am I doing something dumb or is there something wrong with the template?

**Comment by millerds** [comment]
Try clearing out the office add-in https://docs.microsoft.com/en-us/office/dev/add-ins/testing/clear-cache.

**Comment by jasperchan** [comment]
I forgot to add that was the first thing I tried.

**Comment by millerds** [comment]
From what I can tell this is expected since the functions file that is being used isn't loaded in the webview, but is being hosted in an excel process (or something like that) which doesn't support hot reload.  This could be different in the case of shared runtime.

**Comment by celluj34** [comment]
> shared runtime

I am using the shared runtime, and get the same error.

**Comment by eGuesdon** [comment]
Hi to all,

Don't know if you either solved your problem but i met the same issue.

I did following steps

#1 - Clear Cache
#2 - Delete package-lock-json file
#3 - Delete dist folder
#4 - Execute the followings command
        #4.1 - npm install custom-functions-metadata-plugin
        #4.2 - npm fund
        #4.3 - npm run build
#5 - Execute : npm run dev-server
#6 - Execute : npm run start

from my side - osx : 12.5.1 - excel : 16.64 (22081401) - that works 1 time. I mean :

- CustomTab --> ok
- TaskPane --> ok
- Custom functions --> ok

BUT... there is always a "BUT"

If i change anything in source code... i get the same error.
I'm still looking for a solution to work live without having to reinstall, rebuild, relaunch.... bla bla bla

hope this help

regards

**Comment by GeeWee** [comment]
I can confirm that changing `functions.js` to be at the end of my webpack configuration file as @eGuesdon suggests works.

I'm honestly a bit surprised that the official quickstart examples are broken.

**Comment by millerds** [comment]
An update to the custom functions templates (ts and js) was recently published that improved some performance issues and made that adjustment of the entry order suggested here.  Are you still encountering this problem?

**Comment by GeeWee** [comment]
Ah, perhaps in that case it will work. I actually gave up developing custom functions because the initial setup was so broken - just wanted to make sure this wasn't auto-closed without any actual action on someones part :)

**Comment by asolopovas** [comment]
I really love the concept that I can devolop custom function in excel, its the best software that I ever used, it only is a shame that nobady cares about these little things that make little people happy...
