### ISSUE TITLE
Accessing Sheet Properties fro Custom Functions 

### ISSUE THREAD

**Issue by PeterTippett** [OfficeDev/Excel-Custom-Functions#32]
When I do this call, it returns nothing when using "Custom Functions".  The same code works with the  Addin model.  I actually want to share data between two Add-ins.

I expect the problem is loading the context.

Sample Code that is used in both.

```
var setProperty("MasterKey", "xxx");
var reply = getProperty("MasterKey");

function getProperty(name) {
    
    var setting = Office.context.document.settings.get(name);
    console.log("ReadSettings: "+ name+", "+setting);
    if (setting == ""){
        return null;
    } else {
        return setting;
    }
}


function setProperty(name, data) {
    console.log("setSetting: "+name+":"+data);
    Office.context.document.settings.set(name, data);
    Office.context.document.settings.saveAsync(function (asyncResult) {
        console.log('set settings saved with status: ' + name + " - "+ data + ", " + asyncResult.status);
    });
}
```

**Comment by mscharlock** [comment]
Hi @PeterTippett, thanks for writing in! The custom functions engineers are hard at work on a solution for this problem as we speak! I believe we will have a blog post with some information I can point you to very soon.

**Comment by mscharlock** [comment]
Hi @PeterTippett - please check out the new changes to custom functions. The latest changes have introduced a new JavaScript runtime and AsyncStorage, which should allow you to share data between add-ins. Documentation can be found here: https://docs.microsoft.com/en-us/office/dev/add-ins/excel/custom-functions-runtime. Let me know if you need additional help!

**Comment by PeterTippett** [comment]
Thanks for this. Need to have a full working example as current access the AsyncStorage call for some reason. How is this new code base accessed?

**Comment by PeterTippett** [comment]
Accessing the new Runtime so can use the Asycn Function, but not working.

This line from the documentation seems to imply that this only works with Addins that have normal UI activity. This implies that can now have custom functions as part of the normal Addins.

Only custom functions within an add-in will use the new JavaScript runtime that's described in this article. If an add-in includes other components such as task panes and other UI elements, in addition to custom functions, these other components of the add-in will continue to run in the browser-like WebView runtime. Additionally:

**Comment by keyur32** [comment]
(copying response from separate thread)

Hey Peter,

Given custom functions execute during Excel's calculation chain, we want to make sure the APIs we expose can work consistently across all platforms. Last week, we updated the runtime on Excel Insiders: https://docs.microsoft.com/en-us/office/dev/add-ins/excel/custom-functions-runtime.

On Desktop and eventually MAC versions, you will only have access to a the APIs described there. We're still working on guidance to expose other OfficeJS APis (plan is to expose any read operations, but any set/save operatations that change the document will not be supported through the custom functions runtime).

Can you describe the scenario you were trying to accomplish?

**Comment by mscharlock** [comment]
Hi @PeterTippett - I believe this issue was solved on a separate thread so I'm going to close this issue, but please let me know if you would like me to reopen it, happy to do so.
