### ISSUE TITLE
Taskpane.html referencing css file that no longer exists

### ISSUE THREAD

**Issue by svickers** [OfficeDev/Excel-Custom-Functions#323]
See this line:
https://github.com/OfficeDev/Excel-Custom-Functions/blob/master/src/taskpane/taskpane.html#L17

CSS file results in a 404.

**Comment by davidchesnut** [comment]
Maybe @millerds should take a look at this? Looks like a yo office template issue.

**Comment by davidchesnut** [comment]
Hi @millerds, Hey I was taking a look at this and the css link for 11.0.1 is broken. But this older link still works. Why would the latest version not be working?

This works: https://static2.sharepointonline.com/files/fabric/office-ui-fabric-core/9.6.1/css/fabric.min.css

**Comment by millerds** [comment]
My guess is that it was a typo when updating the link (it should be 11.0.0 I think).  I plan on correcting this as I update the templates soon.

**Comment by millerds** [comment]
I doing some PRs to push out template updates now that will correct this.  Should be good in the next day or two.

**Comment by millerds** [comment]
This is now corrected in the live templates
