### ISSUE TITLE
Custom Functions remain after add-in uninstalled

### ISSUE THREAD

**Issue by andrewkittredge** [OfficeDev/Excel-Custom-Functions#326]
Our add-in defines custom functions.  A user installed the add-in from the Office store. Then uninstalled the add-in.  After they uninstalled the add-in they still see the custom functions.

I have them follow the instructions @ https://docs.microsoft.com/en-us/office/dev/add-ins/testing/clear-cache#clear-the-office-cache-on-windows to no avail.

**Comment by millerds** [comment]
Can you explain more about what "they still see the custom functions" means?  Do you mean the function added to the cell wasn't removed or you were still able to add the same function to another cell or something else?

Did you shut down Excel while clearing the cache?

**Comment by andrewkittredge** [comment]
This is a bug.

The user has uninstalled the javascript add-in but our custom functions still show in the autocomplete when they type `=CALCBENCHDATA`.

This is a problem because the names collide with the UDFs from our desktop add-in.

**Comment by millerds** [comment]
This repo is for developer tooling to build Excel Custom functions.  That sounds like a problem with the cache remaining in Excel after an add-in has been removed (dev tooling not involved).  Sounds like good feedback for the Excel team.
