### ISSUE TITLE
No access to Customfunctions namespace 

### ISSUE THREAD

**Issue by RaoulRSV** [OfficeDev/Excel-Custom-Functions#335]
I am developping an Excel web addin on Visual Studio 2022 with customs functions and a server part
and I am unable to access to the CustomFunctions namespace.
Here under : part of XML, Functions.Json file, Functions.ts file, impact on excel
![image](https://user-images.githubusercontent.com/54595398/176657311-c44a802f-a3aa-4ac5-a9d7-d400e70ea7c7.png)
![image](https://user-images.githubusercontent.com/54595398/176656465-e523de45-51e8-4e28-8dd1-901cb0307bef.png)
![image](https://user-images.githubusercontent.com/54595398/176656512-860e0ecc-1519-4dea-8a98-63bd0c82a60c.png)
![image](https://user-images.githubusercontent.com/54595398/176660191-8d2b1689-c92d-4fbf-8be0-a90eb0a63ea0.png)

Note that developping this custom functions with Visual studio code  is quite straightforward but provides no clue as far as my project is concerned.
Please provide hints
Sincerly

**Comment by grangeryy** [comment]
Thank you @RaoulRSV for reporting the issue. I've added @yaweizhu-henson to take a look

**Comment by RaoulRSV** [comment]
@yaweizhu-henson : thank you to care about this question.
 Do you need any further explaination ?

**Comment by yaweizhu-henson** [comment]
So sorry for this super late response.
I will let engineer have a look at this issue ASAP

**Comment by RaoulRSV** [comment]
Thanks a lot

Le lun. 25 juil. 2022 à 16:04, yaweizhu-henson ***@***.***> a
écrit :

**Comment by JHJ-MS** [comment]
Hi @RaoulRSV , sorry for this super late response. I suggest you install the Yeoman generator and choose a CF-Addin template to generate a CF-Addin project.[Build your first custom functions project](https://learn.microsoft.com/en-us/office/dev/add-ins/quickstarts/excel-custom-functions-quickstart?tabs=excel-windows)

Thanks

**Comment by RaoulRSV** [comment]
Thanks for your answer.As I wrote in my request I did already know this
possibility,  however I cannot use it for this project because this project
includes a heavy c# server.
Alternatively, you may know how to add a Visual Studio 2022 project to a
Yeoman project that already includes custom functions.
Sincerely

**Comment by millerds** [comment]
In the screen shot the namespace casing is wrong . . . it shows "Customfunctions" instead of "CustomFunctions" (which is correct in the comment above it).

**Comment by RaoulRSV** [comment]
Thank you for your answer, but the issue is that issue is that
 Customsfunctions whatever the case is not activated in my code even though
it customs function its initialized  in a html.
Sincerely

Le jeu. 17 nov. 2022 à 18:32, Darren Miller ***@***.***> a
écrit :

**Comment by davidchesnut** [comment]
Hi @RaoulRSV, Is the functions.ts actually getting loaded as part of the project? You can test this by moving the custom function code into your taskpane.js. This will work with shared runtime as you are not required to use a functions file. If the code starts working, then I'd check to see what's happening with functions.ts. 

Also you can debug using the browser developer tools by loading the add-in into Excel on the web. Then check the console to see if any errors are getting reported (you can also check that functions.ts and other files were actually loaded.)

Hope this helps,
David

**Comment by RaoulRSV** [comment]
Thank you I’ll try that and report to you

Le lun. 28 nov. 2022 à 20:23, David Chesnut ***@***.***> a
écrit :

**Comment by RaoulRSV** [comment]
Sorry @David Chestnut, I couldn't solve it this way

**Comment by davidchesnut** [comment]
Hi @RaoulRSV,

I put together a working project which you can see here. [Visual Studio custom function demo](https://github.com/davidchesnut/vs-custom-function-demo). I started with the basic Excel template in VS 2022, then built a yo office custom function project and integrated it. You might compare and contrast with your own project. 

I discovered some interesting things you need to handle manually that yo office typically takes care of. Any of these missing steps can trip up your custom functions.
- You need to specifically include the functions.js file in your home.html file. Load it after Office JS or it won't see the CustomFunctions namespace.
- You need to add CustomFunctions.assocate calls for each function you have (see functions.js)
- You need to handle CORS. In the web.config I set to allow * headers, which is okay for testing, but set these values appropriately when you get to deployment.
- You need to build the functions.json manually (you only need to reference it from the manifest XML.)

Hope this helps!
David

**Comment by RaoulRSV** [comment]
Sorry, I haven't seen your answer until now. Thanks a lot for your sample
that I did test successfully.

I will work on it. I might some additional while I am on typescript

That will help
Raoul


Le lun. 19 déc. 2022 à 01:01, David Chesnut ***@***.***> a
écrit :

**Comment by RaoulRSV** [comment]
I did convert your sample to typescript but failed to have the custom
functions working properly : they send a  "#value!" result.
Would you have any suggestions?
Sincerely
Raoul

**Comment by RaoulRSV** [comment]
Finally I succeeded with your sample after converting it to typescript.
Only thing to do is to exclude  "function.ts" file in tsconfig.json and to
keep a function.js in the project files.
I have still some work to do in order to align my project to your sample.
It should be easy now.
Thanks a lot?

Raoul
