### ISSUE TITLE
Custom functions do not run unless I press Enter

### ISSUE THREAD

**Issue by tqdo** [OfficeDev/Excel-Custom-Functions#339]
I have an Excel add-on which includes a custom function. From my website, I use a Javascript library [SheetJS](https://docs.sheetjs.com/docs/csf/features/formulae/#dynamic-array-formulae) to create an Excel file which includes the custom function. When I open the Excel file, the custom function is display correctly like this: =CustomFunction(para1, para2). However, it is not run/evaluated automatically. Only if I double click on a cell which contains the custom function, then either Enter or click another cell, then the original cell which contains the custom function is evaluated. 

Just wondering whether there is anyway to fix this and make the custom function to run without having to manually press Enter for each cell? Thanks

**Comment by rundongmsft** [comment]
Hi @tqdo, I have an idea for run CFs automatically: Try this API [`context.application.calculate('FullRebuild');`](https://docs.microsoft.com/zh-cn/javascript/api/excel/excel.application?view=excel-js-preview#excel-excel-application-calculate-member(2)). It will rebuild the dependences of each function and recalculate them.

**Comment by tqdo** [comment]
Hi, it still does not work. Sorry I should have been clearer. The custom functions are not automatically run probably because Excel does not recognize them (the cells which contain the custom functions initially show #NAME?). But somehow after I go to those cells and press Enter, then Excel recognizes that function name and runs it.

**Comment by rundongmsft** [comment]
Hi @tqdo, Excel recognizes the CFs in one file by checking the `webextension[x].xml` of this file:
![image](https://user-images.githubusercontent.com/73267941/182566743-376abcef-596d-4568-acae-60d37f9d6d40.png)
You can change the extension of the file SheetJS created from '.xlsx' to '.zip', unzip it. check whether `webextension[x].xml` exist and whether `webextension.xml` contains definitions of your CFs. If no, that means SheetJS cannot create workbook with CFs correctly. If yes, please share your file with me for further analysis.
