### ISSUE TITLE
console.log() for a Custom Function in Shared Runtime goes nowhere

### ISSUE THREAD

**Issue by adammpolak** [OfficeDev/Excel-Custom-Functions#350]
# Prerequisites

Please answer the following questions before submitting an issue. 
**YOU MAY DELETE THE PREREQUISITES SECTION.**
- I am running Node v16 (v18 doesn't work with the yo generator, I filed a ticket)
- I checked the documentation and found no answer (I have done everything and then some)
- I checked to make sure that this issue has not already been filed

# Expected behavior

If I put console.log() in a custom function it should log somewhere, like OfficeAddins.log.txt

Or in the debugger if I run from vscode

# Current behavior

There is no console.log() anywhere

## Steps to Reproduce

Try to get a console.log() of a custom function using a shared runtime from the yo generator project and it will not work.

## Context

Please provide any relevant information about your setup. This is important in case the issue is not reproducible except for under certain conditions.

* Operating System: Latest windows
* Node version: 16
* Office version: Latest
* Tool version: Latest

## Failure Logs

Please include any relevant log snippets, screenshots or code samples here.

```
11/12/2022 14:11:33	Verbose	CustomFunctions	[Execution] [Async] [Begin] Function=CONTOSO.FRENCHQUESTIONTWO, Workbook=Excel add-in 9f662e46-0311-4a4a-be5e-dbb7797a8b6c.xlsx		
11/12/2022 14:11:33	Unexpected	CustomFunctions	[Execution] [Async] [End] [Failure] Function=FRENCHQUESTIONTWO, Workbook=Excel add-in 9f662e46-0311-4a4a-be5e-dbb7797a8b6c.xlsx		
```

This is what in the output log, there is no console.log() appearing

**Comment by akrantz** [comment]
Enable runtime logging and the log messages will go to the runtime log.

https://learn.microsoft.com/en-us/office/dev/add-ins/testing/runtime-logging

**Comment by adammpolak** [comment]
the key is that you need to add "export" or it does not go to the runtime log. That is not listed in documentation, you might want to add that.
