### ISSUE TITLE
Can browserslist be updated beyond ie 11

### ISSUE THREAD

**Issue by mcshaz** [OfficeDev/Excel-Custom-Functions#359]
Can the browserslist be updated to more a more modern browser than ie 11? This will reduce bundle size significantly.

**Comment by millerds** [comment]
You can change you project to support what you want.  The default is there because some older version of office (still supported by Microsoft) use the ie11 control to run.  See https://learn.microsoft.com/en-us/office/dev/add-ins/concepts/browsers-used-by-office-web-add-ins for the details.

**Comment by nkkinariwala** [comment]
@mcshaz - can you please let us know if comments provided by Darren work for you?

**Comment by mcshaz** [comment]
Closing as the comment answers the question. I would think it is time to drop all support for ie11, and designing new software with ie11 in mind in 2023 is unnecessary, thus the office add-on templates should have this removed from supported  browserslist. Also the question of which versions of legacy edge (Web view 1) need support, but hard to know without seeing LTS schedules and use statistics relating to office for web
