### ISSUE TITLE
[Help] how to combine Angular template with custom functions

### ISSUE THREAD

**Issue by celluj34** [OfficeDev/Excel-Custom-Functions#365]
Hello;

If this is not the correct repository for this issue, please let me know.

I want to create an excel add-in that uses angular in the taskpane (and dialogs), but also have custom functions available on the sheet. The yo templates have these available separately, but what's the best way to leverage the angular framework in the custom functions?

What I mean is, if I'm using angular to run the html, is there a way to "hook" into that so I can reuse everything (`fetch`, DI, , error checking, etc) that I've set up within angular?

**Comment by millerds** [comment]
Are you saying you want use angular in the Custom Functions themselves?  I'm not familiar enough with angular to know how well that would work (or how helpful it would be).  

At its core CF is the functions file defining the functions to run as part of formulas in Excel combined with manifest changes to indicating the function retrieval and a json metadata file (generated by webpack in this project).  The taskpane isn't required or involved.  I'm guessing your scenario might be more complex than that.  

You could try using Angular in the functions file, but I'm guessing you'd have to do something with the transpilation process to get the functions js output and it's corresponding json file generated such that it could be retrieved by the Excel when it loads the manifest.

**Comment by akrantz** [comment]
The custom functions run in a separate non-browser JavaScript runtime from the regular add-in code which runs in the webview taskpane. If you want to have the custom functions run from the same webview as the taskpane, you need to configure it to use the shared runtime. This could allow the custom function code to call into other functions from the taskpane.

I'm not sure if there's a sample of custom functions using the shread runtime. 

Here's docs for using the shared runtime.
https://learn.microsoft.com/en-us/office/dev/add-ins/develop/configure-your-add-in-to-use-a-shared-runtime

The custom functions would be in the same bundle as the taskpane, rather than a separate functions.js bundle.

**Comment by millerds** [comment]
Yes that is and it is hooked up to generator-office options and being maintained with similar fixes to master.

**Comment by celluj34** [comment]
Here's an example of what I'm looking for.

Say I have some data being loaded from an API that I want to show in the taskpane. I have set up an angular service (call it ThingService) to load that data, display it in the taskpane, style it, etc.

But now I have a custom function that would load the same or similar data and write it to the sheet. How would I re-use ThingService in a custom function so I don't have to rewrite my data access?

**Comment by millerds** [comment]
You safest bet would be to try with the Custom Functions in Shared Runtime project, add the angular code there, and in the functions file just reference and call the angular service from the CF function.

**Comment by celluj34** [comment]
Perhaps this is getting more into the "how-to with angular" than specifically office add-ins.

But how do I "hook" into the angular app from "outside" of it? The angular app is bootstrapped from Office.onReady but there's no equivalent for custom functions (or ribbon commands). I can't just `import {ThingService} from "../services"` and `const thingService = new ThingService()` if there are dependencies. That would also not include things like interceptors which would add the auth header or error handling.

An idea I had was to use events on the window (since we would use the SharedRuntime) so that when a formula was invoked, the angular app would listen and handle the `invocation` natively within the angular framework. Does something like that sound feasible?

**Comment by millerds** [comment]
I think I get your point now . . . but this is moving further into Angular then I'm familiar with.  You'd have to play with it to see if you can make it work.  You could also ask the questions on StackOverflow where you might get more people familiar with Angular to respond.

**Comment by celluj34** [comment]
Yeah that's kinda what I figured. Thanks for taking the time to chat! I'll comment again if I find a decent solution.
