### ISSUE TITLE
Cells with custom functions not calculating / refreshing on opening the workbook

### ISSUE THREAD

**Issue by ilex-sgangwani** [OfficeDev/Excel-Custom-Functions#368]
Hi all,

I have an Excel add-in that exposes a custom function to the users. The functions work fine when I create the sheet with all the formulas, however, when I save and open the workbook again, the formulas don't trigger automatically, thereby, showing stale data. I have checked my sheet that the Formulas are set to Automatic. Not sure what is wrong but struggling to make this work correctly.
The custom function is calling a webAPI to get the result and has been implemented as a single function as well as with batching but the issue persists.

**Comment by ilex-sgangwani** [comment]
I might have answered this myself but is it because my functions aren't registered as volatile?

**Comment by AlexJerabek** [comment]
Hi @ilex-sgangwani,

You are correct. Only [volatile functions](https://learn.microsoft.com/en-us/office/dev/add-ins/excel/custom-functions-volatile) are recalculated on workbook open.

I'm going to close this issue. If you have questions about how to implement that feature or other learning questions, please raise issues on the [Office Add-ins documentation repo](https://github.com/OfficeDev/office-js-docs-pr).
