### ISSUE TITLE
Sample function is slow to execute

### ISSUE THREAD

**Issue by OwenTrokeBillard** [OfficeDev/Excel-Custom-Functions#372]
Hello. The `CONTOSO.ADD` sample function has a very noticeable delay when executing. It is especially slow when many invocations are chained. Is this normal? What might cause this delay?

# Expected behavior

The `CONTOSO.ADD` sample function executes immediately.

# Current behavior

The `CONTOSO.ADD` sample function takes about half a second to execute and displays `#BUSY!` while calculating.

## Steps to Reproduce

1. Insert integer values into cells A1 and B1.
2. Set cell C1 to the formula `=CONTOSO.ADD(A1,B1)`.
3. Observe that the value of C1 takes about half a second to update when A1 or B1 changes, and meanwhile displays `#BUSY!`.
4. Chain invocations (add B1 C1, C1 D1, D1 E1, ...) to make the effect more pronounced.

## Context

* Operating System: Windows Desktop and Web
* Node version: 18.16.0 LTS
* Office version: 2304
* Tool version: generator-office 1.9.6

**Comment by davidchesnut** [comment]
Hi @OwenTrokeBillard, sorry there was a shift in ownership areas and this issue got lost in the shuffle. @kkmanwilliam is this something you could help out with? BTW: I reproduced this issue and the chaining of the custom functions does indeed get quite slow.

Thanks!
David

**Comment by donlvMSFT** [comment]
Hi @eddeuser ,

We're trying to locate the issue, ideally, because of the calc dependency, chained formulas would be much slower than parallel execution. 

For Excel Custom Function specific scenario, the delay would be more visible for web version, because there would be more web connection time from Browser to Server, Server to Add-in, and backward. On Desktop version, the performance is much better. 

If you are facing the delay issues on desktop version, that could be severe, please share your snippet and we need to investigate more. Is the escalation related? Could you brief?

The product group is keep working on improve the performance experience, thanks for reporting this.

Thanks.

**Comment by eddeuser** [comment]
Our issue is with desktop version.
________________________________

**Comment by eddeuser** [comment]
I am facing #Busy and then it shows an error message in the addin. Enclosed is the case with MS and the detailed notes:

Ed

From: Deuser, Ed ***@***.***>
Date: Tuesday, September 12, 2023 at 7:00 AM
To: OfficeDev/Excel-Custom-Functions ***@***.***>, OfficeDev/Excel-Custom-Functions ***@***.***>
Cc: Mention ***@***.***>
Subject: Re: [OfficeDev/Excel-Custom-Functions] Sample function is slow to execute (Issue #372)
Our issue is with desktop version.
________________________________

**Comment by donlvMSFT** [comment]
Hi @eddeuser , could you share the error message shown in the add-in? 

And also are you using the sample Add-in like CONTOSO ones?

Thanks.

**Comment by donlvMSFT** [comment]
Hi @eddeuser ,

Are you seeing "Restart" add-in error after "We're starting the add-ins runtime, just a moment..." in the status bar?

![Screenshot 2023-09-13 190942](https://github.com/OfficeDev/Excel-Custom-Functions/assets/42738188/f1b40dd5-0591-419c-a05c-b404dae9ab44)

If not, please share more details to the behavior.

Also, could share some information to help us locate the issue?
1. Office version
2. Windows version
3. If you have admin access to C:\Windows\System32, please share the version number of Windows.Storage.OneCore.dll

Thanks.

**Comment by eddeuser** [comment]
we resolved the issue by replacing the following resid="Functions.Script.Url" in <Runtimes> with the following : 
resid="Taskpane.Url"

**Comment by donlvMSFT** [comment]
Hi @eddeuser ,

Glad to know the issue is resolved.

Thanks,
