### ISSUE TITLE
Custom Function gets stuck on BUSY after correcting an error in Excel for Web

### ISSUE THREAD

**Issue by titanous** [OfficeDev/Excel-Custom-Functions#376]
# Expected behavior

Custom function does not show BUSY.

# Current behavior

After editing a cell to correct an error in a call to a custom function, it shows BUSY.

## Steps to Reproduce

1. Use a custom function in a cell that returns an error, for example based on invalid arguments. The cell shows `VALUE` due to the error.
2. Edit the formula in the cell to correct the arguments so that they are correct.
3. Instead of showing the value from the custom function, the function is never called and shows `BUSY` forever.

## Context

Please provide any relevant information about your setup. This is important in case the issue is not reproducible except for under certain conditions.

* Office version: Excel for Web on Chrome and Safari (works fine in Excel for Windows/Mac)

**Comment by jiju-MS** [comment]
Hey, titanous, may I ask is it happened for your test add-in in local environment or any store add-in?

**Comment by titanous** [comment]
@jiju-MS Yes, this happens consistently for the development version and our store add-in.

**Comment by ZYUN-MSFT** [comment]
Hi @titanous , 

Would you please help to provided more detail repro steps? That would help a lot for locate the issue.

Thanks.

**Comment by ZYUN-MSFT** [comment]
Hi @titanous ,

Kindly ping this.

Please share the more detail repro steps of this. A minimal repro code gist would be a lot of helpful
![image](https://github.com/OfficeDev/Excel-Custom-Functions/assets/122421505/899b064b-7ec1-4f0d-b2b7-cf9cfbeaa307)

Thanks.
