### ISSUE TITLE
Issue with custom functions in web excel deployed as custom apps in admin center

### ISSUE THREAD

**Issue by Nikodem98** [OfficeDev/Excel-Custom-Functions#418]
# Current behavior

When I open a spreadsheet on web excel I get "Error installing functions"
![image](https://github.com/OfficeDev/Excel-Custom-Functions/assets/67469274/d57e6e26-f52a-4326-8c22-0264040e60b0)
but when I re-add the admin Home -> add-ins -> admin managed -> add that admin again everything loads correctly.
on desktop app for Mac and windows everything works correctly.

Same happens on every browser

**Comment by AlexJerabek** [comment]
Thank you for reporting this @Nikodem98.

@grangeryy, could you please investigate?
