### ISSUE TITLE
Volatile Function

### ISSUE THREAD

**Issue by mehdigolari** [OfficeDev/Excel-Custom-Functions#5]
We need to be able to mark certain custom function as "volatile". I was not able to find this and I was wondering if you currently support this or will support this in near future. Thanks!

**Comment by saunders77** [comment]
Thanks for the comment! It's not supported now, but it's something we've heard from other customers. As usual, I can't give dates, but it's a feature we're considering for the future.

**Comment by mehdigolari** [comment]
Michael -- Thanks for the prompt response. This would be greatly appreciated.

**Comment by keyur32** [comment]
Update: this feature is under development and we're working hard to make it available in the January update to the Office Insiders build. Will let you know when it is available.

**Comment by mscharlock** [comment]
Also a note: This feature has been documented in advance of release if you want to check it out! Release of the bits that support this feature should be imminent (next week and a half or so).

**Comment by delium** [comment]
should this already supposed to work in excel online? my build is 16.0.11506.35050
also the scheme does not include volatile option:
https://developer.microsoft.com/en-us/json-schemas/office-js/custom-functions.schema.json

**Comment by keyur32** [comment]
Hi, I just looks like this hasn't rolled out to all versions on Excel Online. I added the awaiting prod deployment until I can verify on Excel Online environments.

**Comment by keyur32** [comment]
I need to update the schema as well but you can still use it on Desktop afiak.

**Comment by keyur32** [comment]
Excel Online is now updated with Volatile Functions!
