### ISSUE TITLE
Calculation speed on Mac

### ISSUE THREAD

**Issue by gmichaud** [OfficeDev/Excel-Custom-Functions#57]
I'm evaluating the feasibility of migrating our .NET Excel add-in and custom functions library to the new JavaScript custom functions. The performance on Mac for the simple functions seems really poor; is that a known issue? Here's a sample using the CONTOSO.ADD function: http://recordit.co/madOVzAHAH. What kind of performance can we reasonably expect once this becomes generally available?

**Comment by keyur32** [comment]
Hi @gmichaud, thanks for trying this out. Can you provide more details of your .net add-in? i.e. is it a COM based automation add-in or does it compile down to an .xll?
  
Goal is to be as fast/faster than VBA UDFs.  By default, functions will run in their own seperate app container (this is running on Windows currently via the custom functions runtime. See https://aka.ms/customfunctions for more info).   

- Currently on Mac, we're running the function code under a webkit process. This will be updated to use the customfunctions runtime, which will have a lower memory footprint.  In the video, it appeared you were just entering this. If so, it could be Excel spinning a webkit process. Subsequent executions will be quicker.

- We're also working on the ability for IT admins to optionally trust and run custom functions in-process for any web add-ins they trust and deploy to your organization. By doing so, this will give the ability to participate in Multi-threaded recalc and get better performance than VBA.

Last, we're still in developer preview and we'll be working on performance for Mac (we're currently focused on the Windows and Online versions).  We're also looking for partners who can help validate JavaScript Custom Functions meets your needs, so would love to chat more and learn. Will reach out to your GH email to sync.

thanks for checking us out.

**Comment by gmichaud** [comment]
Hi @keyur32, thanks for your reply. [Our product](www.velixo.com) is a set of functions and tools that allow you to build financial statements with live data coming from an ERP/accounting system. It is a C# library that's packed into a XLL with the help of [ExcelDNA](https://github.com/Excel-DNA/ExcelDna). We connect to a cloud-based ERP and to achieve the best possible performance we synchronize data to a local SQLite database (that's entirely transparent for the user). Some of our customers have spreadsheets that consolidate data from multiple tenants/companies, and the spreadsheets often contain 60,000+ individual function calls to our XLL. It would make no sense to issue separate SQL queries for each function call - we use the SQLite only for data storage and lazy-load the data in memory. Calculations are done using an async/multi-threaded calculation engine. The largest spreadsheets that we have seen can be fully recalculated in 1-2 minutes, but for more typical cases it's around 15-30 seconds. 

With this new JavaScript-based engine my expectations are that the performance will be slower, but i'd like to stay close to what we have today. I definitely think that I need to move the calculation and caching logic to the back-end, and batch XMLHttpRequests to the server (I recall seeing a question/sample here or on Stackoverflow). But first I wanted to try the absolute simplest example.

You are 100% right that I was just entering the function. Following your reply to my question I tried it again, and subsequent requests are sometimes faster, but not always. Is it possible that the webkit process gets shut down quickly if it's not needed? I suspect that you have your custom functions runtime that things will be more consistent. Here's another recording: http://recordit.co/L7kvrOfYRO

- 1st calc: 1 cell, 10 seconds
- 2nd calc: 4 cells, instant
- 3rd calc: 9 cells, 9 seconds
- 4th calc: this one is interesting, shortly before Excel returns results for the cell I added, I copy the formula to the cell below it. The results for both cells are returned right away.

I have yet to try it on Excel for Windows but will do so soon. Here's the same thing with Excel Online: http://recordit.co/enBT7SsBfY - it is slightly slower than the built-in functions but in my opinion more than acceptable.

**Comment by keyur32** [comment]
Hi Gabriel, just came back to to this and marking as under investigation. We're going to start looking at Mac performance after the holidays so we'll see what is possible here.

**Comment by keyur32** [comment]
Will keep you updated on our weekly call ;)

**Comment by keyur32** [comment]
I think we had followed up offline but for our V1 GA, you should expect to see similiar performance of Function calls on Mac and Excel online. We've optimized for web requests specifically (majority of the scenarios have centered around this), and in the future we'll be looking at improving speed for functions that are doing client side calculations.
