### ISSUE TITLE
Custom Functions not working on macOS

### ISSUE THREAD

**Issue by ThorstenHans** [OfficeDev/Excel-Custom-Functions#63]
I've created a sample Add-in to try custom functions in Excel on macOS. 

The Add-in loads correctly but none of the custom functions can be executed from within Excel. Excel just prints `#NAME?`.

macOS: 10.13.6
Excel for Mac: 16.19 Build 181024

Office Insider program is joined by setting insider builds to `Office Insider Fast` in *Microsoft AutoUpdate*

**Comment by TCourtneyOwen** [comment]
I haven't had a chance to check out custom functions on Mac personally, but I opened a bug a few weeks back about CFs not working on Mac and the bug was resolved back to me this morning as fixed with the following comment: "Fixed by publishing mac js version on github."

-Courtney

**Comment by akrantz** [comment]
@ThorstenHans I tried it today on Mac and it worked. Please re-open if you are still having issues.
