### ISSUE TITLE
Can user use the custom function in normal version?

### ISSUE THREAD

**Issue by hanzhangyu** [OfficeDev/Excel-Custom-Functions#7]
In the latest of `insider version`, it works. but my users are not in the `insider version`. I worried about that it dont works. 

If there are some plan in the progress , please let know. Thank you.

**Comment by saunders77** [comment]
We haven't yet announced the date when it will be Generally Available to all Excel users yet. For now it's just insiders. Sorry for the wait!

**Comment by bsmartt13** [comment]
This is deeply concerning to me, as a defender. I really hope this is off by default if it ever goes into GA.

**Comment by keyur32** [comment]
Marking issue closed. feel free to reopen!
