### ISSUE TITLE
function stockPrice(ticker) doesn't work in 1901 build

### ISSUE THREAD

**Issue by eldargum** [OfficeDev/Excel-Custom-Functions#87]
Hi! in the previous version the custom function works fine, and now the error #VALUE! is returned.

Following the instructions in: [Excel custom functions tutorial (preview) - Office Add-ins](https://docs.microsoft.com/en-us/office/dev/add-ins/tutorials/excel-tutorial-create-custom-functions?tabs=excel-windows)

**Comment by kbrandl** [comment]
@eldargum thanks for reporting this issue. Since this sounds like a product issue (not a documentation issue), I've transferred it to the OfficeDev/Excel-Custom-Functions repo, which members of the product team monitor for issues like this.

**Comment by akrantz** [comment]
There is a known bug with XHR in the build which is causing this. A fix is being worked on.

**Comment by keyur32** [comment]
Hi @eldargum, apologies! We introduced a pair of impacting bugs that are currently being fixed:

a) fetch calls in the 1901 build fail on windows. They should work on Excel Online. As a workaround, you can use XMLHTTPRequest (XHR) to make the call. See [this ScriptLab add-in gist]((https://gist.github.com/keyur32/bf0d9a41493b510e8e640c7624db1862)) which has a stockprice example using XHR, which should still work 

b) XHR also has a bug that may impact you as there is an extra character being passed back in the response header. If your function needs to read only the response body (more common), then this will work. 

We will update the documentation shortly.

**Comment by eldargum** [comment]
@keyur32 , thanks for explaining!
